### ISSUE TITLE
title и actionbar не работают в  1.17

### ISSUE THREAD

**Issue by Levakiv** [Brikster/Chatty#124]
Title и actionbar не работают на spigot 1.17
Titles:
```
[Server thread/WARN]: [Chatty] Task #13 for Chatty v2.19.2 generated an exception
java.lang.RuntimeException: Titles are not supported by Chatty on your server version (v1_17_R1)
        at ru.mrbrikster.chatty.util.textapi.Title.send(Title.java:108) ~[?:?]
        at ru.mrbrikster.chatty.notifications.TitleNotification.lambda$run$1(TitleNotification.java:58) ~[?:?]
        at java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:183) ~[?:?]
        at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:179) ~[?:?]
        at java.util.AbstractList$RandomAccessSpliterator.forEachRemaining(AbstractList.java:720) ~[?:?]
        at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:484) ~[?:?]
        at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474) ~[?:?]
        at java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:150) ~[?:?]
        at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:173) ~[?:?]
        at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234) ~[?:?]
        at java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:596) ~[?:?]
        at ru.mrbrikster.chatty.notifications.TitleNotification.run(TitleNotification.java:44) ~[?:?]
        at org.bukkit.craftbukkit.v1_17_R1.scheduler.CraftTask.run(CraftTask.java:81) ~[spigot-1.17.jar:3111-Spigot-66f9d3c-cbf2f67]
        at org.bukkit.craftbukkit.v1_17_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:400) ~[spigot-1.17.jar:3111-Spigot-66f9d3c-cbf2f67]
        at net.minecraft.server.MinecraftServer.b(MinecraftServer.java:1251) ~[spigot-1.17.jar:3111-Spigot-66f9d3c-cbf2f67]
        at net.minecraft.server.dedicated.DedicatedServer.b(DedicatedServer.java:436) ~[spigot-1.17.jar:3111-Spigot-66f9d3c-cbf2f67]
        at net.minecraft.server.MinecraftServer.a(MinecraftServer.java:1199) ~[spigot-1.17.jar:3111-Spigot-66f9d3c-cbf2f67]
        at net.minecraft.server.MinecraftServer.x(MinecraftServer.java:1026) ~[spigot-1.17.jar:3111-Spigot-66f9d3c-cbf2f67]
        at net.minecraft.server.MinecraftServer.lambda$0(MinecraftServer.java:307) ~[spigot-1.17.jar:3111-Spigot-66f9d3c-cbf2f67]
        at java.lang.Thread.run(Thread.java:831) [?:?]
Caused by: java.lang.NoSuchFieldException: playerConnection
        at java.lang.Class.getField(Class.java:2086) ~[?:?]
        at ru.mrbrikster.chatty.util.textapi.Title.send(Title.java:86) ~[?:?]
        ... 19 more
```
ActionBar:
```
[Server thread/WARN]: [Chatty] Task #13 for Chatty v2.19.2 generated an exception
java.lang.RuntimeException: ActionBar is not supported by Chatty on your server version (v1_17_R1)
        at ru.mrbrikster.chatty.util.textapi.ActionBar.send(ActionBar.java:104) ~[?:?]
        at ru.mrbrikster.chatty.notifications.ActionBarNotification.lambda$run$1(ActionBarNotification.java:65) ~[?:?]
        at java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:183) ~[?:?]
        at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:179) ~[?:?]
        at java.util.AbstractList$RandomAccessSpliterator.forEachRemaining(AbstractList.java:720) ~[?:?]
        at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:484) ~[?:?]
        at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474) ~[?:?]
        at java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:150) ~[?:?]
        at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:173) ~[?:?]
        at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234) ~[?:?]
        at java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:596) ~[?:?]
        at ru.mrbrikster.chatty.notifications.ActionBarNotification.run(ActionBarNotification.java:63) ~[?:?]
        at org.bukkit.craftbukkit.v1_17_R1.scheduler.CraftTask.run(CraftTask.java:81) ~[spigot-1.17.jar:3111-Spigot-66f9d3c-cbf2f67]
        at org.bukkit.craftbukkit.v1_17_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:400) ~[spigot-1.17.jar:3111-Spigot-66f9d3c-cbf2f67]
        at net.minecraft.server.MinecraftServer.b(MinecraftServer.java:1251) ~[spigot-1.17.jar:3111-Spigot-66f9d3c-cbf2f67]
        at net.minecraft.server.dedicated.DedicatedServer.b(DedicatedServer.java:436) ~[spigot-1.17.jar:3111-Spigot-66f9d3c-cbf2f67]
        at net.minecraft.server.MinecraftServer.a(MinecraftServer.java:1199) ~[spigot-1.17.jar:3111-Spigot-66f9d3c-cbf2f67]
        at net.minecraft.server.MinecraftServer.x(MinecraftServer.java:1026) ~[spigot-1.17.jar:3111-Spigot-66f9d3c-cbf2f67]
        at net.minecraft.server.MinecraftServer.lambda$0(MinecraftServer.java:307) ~[spigot-1.17.jar:3111-Spigot-66f9d3c-cbf2f67]
        at java.lang.Thread.run(Thread.java:831) [?:?]
Caused by: java.lang.ClassNotFoundException: net.minecraft.server.v1_17_R1.IChatBaseComponent
        at org.bukkit.plugin.java.PluginClassLoader.loadClass0(PluginClassLoader.java:142) ~[spigot-1.17.jar:3111-Spigot-66f9d3c-cbf2f67]
        at org.bukkit.plugin.java.PluginClassLoader.loadClass(PluginClassLoader.java:99) ~[spigot-1.17.jar:3111-Spigot-66f9d3c-cbf2f67]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:519) ~[?:?]
        at java.lang.Class.forName0(Native Method) ~[?:?]
        at java.lang.Class.forName(Class.java:375) ~[?:?]
        at ru.mrbrikster.chatty.util.textapi.ServerPackage.getClass(ServerPackage.java:42) ~[?:?]
        at ru.mrbrikster.chatty.util.textapi.ActionBar.send(ActionBar.java:89) ~[?:?]
        ... 19 more
```

**Comment by T1MOXA** [comment]
Та же проблема

**Comment by Brikster** [comment]
Fixed in 0b2dd1e
