### ISSUE TITLE
не работают Json на 1.17

### ISSUE THREAD

**Issue by igumen1990** [Brikster/Chatty#125]
[16:06:50 ERROR]: Could not pass event AsyncPlayerChatEvent to Chatty v2.19.2
java.lang.RuntimeException: Json components is not supported by Chatty on your server version (v1_17_R1)
        at ru.mrbrikster.chatty.util.TextUtil.sendJson(TextUtil.java:153) ~[?:?]
        at ru.mrbrikster.chatty.json.fanciful.FancyMessage.send(FancyMessage.java:487) ~[?:?]
        at ru.mrbrikster.chatty.json.fanciful.FancyMessage.send(FancyMessage.java:512) ~[?:?]
        at ru.mrbrikster.chatty.json.FormattedMessage.send(FormattedMessage.java:32) ~[?:?]
        at ru.mrbrikster.chatty.chat.ChatListener.applyJsonSwears(ChatListener.java:397) ~[?:?]
        at ru.mrbrikster.chatty.chat.ChatListener.performJsonMessage(ChatListener.java:376) ~[?:?]
        at ru.mrbrikster.chatty.chat.ChatListener.onChatMonitor(ChatListener.java:312) ~[?:?]
        at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor130.execute(Unknown Source) ~[?:?]
        at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:69) ~[patched_1.17.jar:git-Paper-"4e2f0be"]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:76) ~[patched_1.17.jar:git-Paper-"4e2f0be"]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[patched_1.17.jar:git-Paper-"4e2f0be"]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:624) ~[patched_1.17.jar:git-Paper-"4e2f0be"]
        at io.papermc.paper.adventure.ChatProcessor.post(ChatProcessor.java:234) ~[patched_1.17.jar:git-Paper-"4e2f0be"]
        at io.papermc.paper.adventure.ChatProcessor.processingLegacyFirst(ChatProcessor.java:116) ~[patched_1.17.jar:git-Paper-"4e2f0be"]
        at io.papermc.paper.adventure.ChatProcessor.process(ChatProcessor.java:65) ~[patched_1.17.jar:git-Paper-"4e2f0be"]
        at net.minecraft.server.network.ServerGamePacketListenerImpl.chat(ServerGamePacketListenerImpl.java:2102) ~[?:?]
        at net.minecraft.server.network.ServerGamePacketListenerImpl.handleChat(ServerGamePacketListenerImpl.java:2013) ~[?:?]
        at net.minecraft.server.network.ServerGamePacketListenerImpl.handleChat(ServerGamePacketListenerImpl.java:1979) ~[?:?]
        at net.minecraft.network.protocol.game.ServerboundChatPacket$1.run(ServerboundChatPacket.java:40) ~[?:?]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515) ~[?:?]
        at java.util.concurrent.FutureTask.run(FutureTask.java:264) ~[?:?]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130) ~[?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630) ~[?:?]
        at java.lang.Thread.run(Thread.java:831) [?:?]
Caused by: java.lang.ClassNotFoundException: net.minecraft.server.v1_17_R1.IChatBaseComponent
        at org.bukkit.plugin.java.PluginClassLoader.loadClass0(PluginClassLoader.java:146) ~[patched_1.17.jar:git-Paper-"4e2f0be"]
        at org.bukkit.plugin.java.PluginClassLoader.loadClass(PluginClassLoader.java:103) ~[patched_1.17.jar:git-Paper-"4e2f0be"]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:519) ~[?:?]
        at java.lang.Class.forName0(Native Method) ~[?:?]
        at java.lang.Class.forName(Class.java:375) ~[?:?]
        at ru.mrbrikster.chatty.util.textapi.ServerPackage.getClass(ServerPackage.java:42) ~[?:?]
        at ru.mrbrikster.chatty.util.TextUtil.sendJson(TextUtil.java:138) ~[?:?]
        ... 23 more

**Comment by vetustus** [comment]
Набросал костыль - https://github.com/vetustus/Chatty/releases/tag/v2.19.2
Решение мне не очень нравится, но это самое очевидное что можно было сделать  https://github.com/vetustus/Chatty/commit/685fbfc745f807625b54bf84c06950143fb48000

**Comment by Brikster** [comment]
Fixed in 0b2dd1e
