### ISSUE TITLE
Обновление до 1.18

### ISSUE THREAD

**Issue by SkyWatcher2019** [Brikster/Chatty#137]
Чат вроде бы работает, но перед отправкой сообщения выбивает ошибку.

```
 [04:56:31 ERROR]: Could not pass event AsyncPlayerChatEvent to Chatty v2.19.4
     java.lang.RuntimeException: NMS features is not supported by Chatty on your server version (v1_18_R1)
         at ru.mrbrikster.chatty.util.textapi.NMSUtil.sendChatPacket(NMSUtil.java:99) ~[Chatty.jar:?]
         at ru.mrbrikster.chatty.json.fanciful.FancyMessage.send(FancyMessage.java:579) ~[Chatty.jar:?]
         at ru.mrbrikster.chatty.json.fanciful.FancyMessage.send(FancyMessage.java:604) ~[Chatty.jar:?]
         at ru.mrbrikster.chatty.json.FormattedMessage.send(FormattedMessage.java:32) ~[Chatty.jar:?]
         at ru.mrbrikster.chatty.chat.ChatListener.performJsonMessage(ChatListener.java:376) ~[Chatty.jar:?]
         at ru.mrbrikster.chatty.chat.ChatListener.onChatMonitor(ChatListener.java:319) ~[Chatty.jar:?]
         at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor202.execute(Unknown Source) ~[?:?]
         at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:69) ~[paper-api-1.18-R0.1-SNAPSHOT.jar:?]
         at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:76) ~[paper-api-1.18-R0.1-SNAPSHOT.jar:git-Paper-35]
         at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[paper-api-1.18-R0.1-SNAPSHOT.jar:?]
         at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:628) ~[paper-api-1.18-R0.1-SNAPSHOT.jar:?]
         at io.papermc.paper.adventure.ChatProcessor.post(ChatProcessor.java:230) ~[paper-1.18.jar:git-Paper-35]
         at io.papermc.paper.adventure.ChatProcessor.processingLegacyFirst(ChatProcessor.java:115) ~[paper-1.18.jar:git-Paper-35]
         at io.papermc.paper.adventure.ChatProcessor.process(ChatProcessor.java:64) ~[paper-1.18.jar:git-Paper-35]
         at net.minecraft.server.network.ServerGamePacketListenerImpl.chat(ServerGamePacketListenerImpl.java:2118) ~[?:?]
         at net.minecraft.server.network.ServerGamePacketListenerImpl.handleChat(ServerGamePacketListenerImpl.java:2029) ~[?:?]
         at net.minecraft.server.network.ServerGamePacketListenerImpl.handleChat(ServerGamePacketListenerImpl.java:1995) ~[?:?]
         at net.minecraft.network.protocol.game.ServerboundChatPacket$1.run(ServerboundChatPacket.java:40) ~[?:?]
         at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) ~[?:?]
         at java.util.concurrent.FutureTask.run(Unknown Source) ~[?:?]
         at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source) ~[?:?]
         at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source) ~[?:?]
         at java.lang.Thread.run(Unknown Source) ~[?:?]
 Caused by: java.lang.NoSuchMethodException: net.minecraft.server.network.PlayerConnection.sendPacket(net.minecraft.network.protocol.Packet)
         at java.lang.Class.getMethod(Unknown Source) ~[?:?]
         at ru.mrbrikster.chatty.util.textapi.NMSUtil.sendChatPacket(NMSUtil.java:96) ~[Chatty.jar:?]
         ... 22 more
 [04:56:31 INFO]: P SkyWatcher_2019: 123
```

**Comment by NONPLAYT** [comment]
1.18 пока не поддержвиается -_-

**Comment by Brikster** [comment]
Пофикшено в 2.19.5
