### ISSUE TITLE
Обновление до 1.18 №2

### ISSUE THREAD

**Issue by B1RDOW** [Brikster/Chatty#138]
1. Перестали работать всплывающие таблички при наведении на ник.  
![Screenshot_120](https://user-images.githubusercontent.com/61405779/144738152-81020f61-ab04-498a-b4c2-b9ab1617a5e4.png)
2. На 1.17 не работает автоматическое написание комманды при нажатии на всплывающую табличку.  
3. Ошибка возникающая перед отправкой сообщения в чат:  

```
[13:28:49] [Async Chat Thread - #0/ERROR]: Could not pass event AsyncPlayerChatEvent to Chatty v2.19.4
java.lang.RuntimeException: NMS features is not supported by Chatty on your server version (v1_18_R1)
	at ru.mrbrikster.chatty.util.textapi.NMSUtil.sendChatPacket(NMSUtil.java:99) ~[Chatty 2.19.4.jar:?]
	at ru.mrbrikster.chatty.json.fanciful.FancyMessage.send(FancyMessage.java:579) ~[Chatty 2.19.4.jar:?]
	at ru.mrbrikster.chatty.json.fanciful.FancyMessage.send(FancyMessage.java:604) ~[Chatty 2.19.4.jar:?]
	at ru.mrbrikster.chatty.json.FormattedMessage.send(FormattedMessage.java:32) ~[Chatty 2.19.4.jar:?]
	at ru.mrbrikster.chatty.chat.ChatListener.performJsonMessage(ChatListener.java:376) ~[Chatty 2.19.4.jar:?]
	at ru.mrbrikster.chatty.chat.ChatListener.onChatMonitor(ChatListener.java:319) ~[Chatty 2.19.4.jar:?]
	at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor70.execute(Unknown Source) ~[?:?]
	at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:69) ~[purpur-api-1.18-R0.1-SNAPSHOT.jar:?]
	at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:76) ~[purpur-api-1.18-R0.1-SNAPSHOT.jar:git-Purpur-"e65c2e3"]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[purpur-api-1.18-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:628) ~[purpur-api-1.18-R0.1-SNAPSHOT.jar:?]
	at io.papermc.paper.adventure.ChatProcessor.post(ChatProcessor.java:230) ~[purpur-1.18.jar:git-Purpur-"e65c2e3"]
	at io.papermc.paper.adventure.ChatProcessor.processingLegacyFirst(ChatProcessor.java:115) ~[purpur-1.18.jar:git-Purpur-"e65c2e3"]
	at io.papermc.paper.adventure.ChatProcessor.process(ChatProcessor.java:64) ~[purpur-1.18.jar:git-Purpur-"e65c2e3"]
	at net.minecraft.server.network.ServerGamePacketListenerImpl.chat(ServerGamePacketListenerImpl.java:2200) ~[?:?]
	at net.minecraft.server.network.ServerGamePacketListenerImpl.handleChat(ServerGamePacketListenerImpl.java:2111) ~[?:?]
	at net.minecraft.server.network.ServerGamePacketListenerImpl.handleChat(ServerGamePacketListenerImpl.java:2077) ~[?:?]
	at net.minecraft.network.protocol.game.ServerboundChatPacket$1.run(ServerboundChatPacket.java:40) ~[?:?]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539) ~[?:?]
	at java.util.concurrent.FutureTask.run(FutureTask.java:264) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) ~[?:?]
	at java.lang.Thread.run(Thread.java:833) ~[?:?]
Caused by: java.lang.NoSuchMethodException: net.minecraft.server.network.PlayerConnection.sendPacket(net.minecraft.network.protocol.Packet)
	at java.lang.Class.getMethod(Class.java:2227) ~[?:?]
	at ru.mrbrikster.chatty.util.textapi.NMSUtil.sendChatPacket(NMSUtil.java:96) ~[Chatty 2.19.4.jar:?]
	... 22 more
[13:28:49] [Async Chat Thread - #0/INFO]: [Java] BIRDOW: df
```

**Comment by NONPLAYT** [comment]
1.18 пока не поддержвиается -_-
Жди пока разраб

**Comment by Brikster** [comment]
#f61cc3f
