### ISSUE TITLE
не работает на Waterfall (Bungeecord форк от PaperMC)

### ISSUE THREAD

**Issue by SPAWNRYS-ban** [Brikster/Chatty#139]
`[16:58:27 WARN]: Error loading plugin Chatty
java.lang.NoClassDefFoundError: org/bukkit/plugin/java/JavaPlugin
	at java.lang.ClassLoader.defineClass1(Native Method) ~[?:?]
	at java.lang.ClassLoader.defineClass(ClassLoader.java:1012) ~[?:?]
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:150) ~[?:?]
	at net.md_5.bungee.api.plugin.PluginClassloader.findClass(PluginClassloader.java:152) ~[waterfall.jar:git:Waterfall-Bootstrap:1.18-R0.1-SNAPSHOT:ab927be:462]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:587) ~[?:?]
	at net.md_5.bungee.api.plugin.PluginClassloader.loadClass0(PluginClassloader.java:66) ~[waterfall.jar:git:Waterfall-Bootstrap:1.18-R0.1-SNAPSHOT:ab927be:462]
	at net.md_5.bungee.api.plugin.PluginClassloader.loadClass(PluginClassloader.java:59) ~[waterfall.jar:git:Waterfall-Bootstrap:1.18-R0.1-SNAPSHOT:ab927be:462]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:520) ~[?:?]
	at java.lang.ClassLoader.defineClass1(Native Method) ~[?:?]
	at java.lang.ClassLoader.defineClass(ClassLoader.java:1012) ~[?:?]
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:150) ~[?:?]
	at net.md_5.bungee.api.plugin.PluginClassloader.findClass(PluginClassloader.java:152) ~[waterfall.jar:git:Waterfall-Bootstrap:1.18-R0.1-SNAPSHOT:ab927be:462]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:587) ~[?:?]
	at net.md_5.bungee.api.plugin.PluginClassloader.loadClass0(PluginClassloader.java:66) ~[waterfall.jar:git:Waterfall-Bootstrap:1.18-R0.1-SNAPSHOT:ab927be:462]
	at net.md_5.bungee.api.plugin.PluginClassloader.loadClass(PluginClassloader.java:59) ~[waterfall.jar:git:Waterfall-Bootstrap:1.18-R0.1-SNAPSHOT:ab927be:462]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:520) ~[?:?]
	at net.md_5.bungee.api.plugin.PluginManager.enablePlugin(PluginManager.java:394) ~[waterfall.jar:git:Waterfall-Bootstrap:1.18-R0.1-SNAPSHOT:ab927be:462]
	at net.md_5.bungee.api.plugin.PluginManager.loadPlugins(PluginManager.java:300) ~[waterfall.jar:git:Waterfall-Bootstrap:1.18-R0.1-SNAPSHOT:ab927be:462]
	at net.md_5.bungee.BungeeCord.start(BungeeCord.java:278) ~[waterfall.jar:git:Waterfall-Bootstrap:1.18-R0.1-SNAPSHOT:ab927be:462]
	at net.md_5.bungee.BungeeCordLauncher.main(BungeeCordLauncher.java:67) ~[waterfall.jar:git:Waterfall-Bootstrap:1.18-R0.1-SNAPSHOT:ab927be:462]
	at net.md_5.bungee.Bootstrap.main(Bootstrap.java:15) ~[waterfall.jar:git:Waterfall-Bootstrap:1.18-R0.1-SNAPSHOT:ab927be:462]
Caused by: java.lang.ClassNotFoundException: org.bukkit.plugin.java.JavaPlugin
	at net.md_5.bungee.api.plugin.PluginClassloader.loadClass0(PluginClassloader.java:103) ~[waterfall.jar:git:Waterfall-Bootstrap:1.18-R0.1-SNAPSHOT:ab927be:462]
	at net.md_5.bungee.api.plugin.PluginClassloader.loadClass(PluginClassloader.java:59) ~[waterfall.jar:git:Waterfall-Bootstrap:1.18-R0.1-SNAPSHOT:ab927be:462]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:520) ~[?:?]
	... 21 more
`
без понятия почему не работает

**Comment by NONPLAYT** [comment]
java.lang.NoClassDefFoundError: **org/bukkit/plugin/java/JavaPlugin**
может быть на вотерфоле не работает

**Comment by Brikster** [comment]
Плагин не предназначен для установки на Waterfall. Функционал, связанный с BungeeCord, работает без этого.
