### ISSUE TITLE
Баг: java.util.UnknownFormatConversionException: Conversion = '%'

### ISSUE THREAD

**Issue by SkyWatcher2019** [Brikster/Chatty#156]
Chatty 2.19.5, Pufferfish 1.18.2
```[20:35:50 ERROR]: Could not pass event AsyncPlayerChatEvent to Chatty v2.19.5
java.util.UnknownFormatConversionException: Conversion = '%'
        at org.bukkit.event.player.AsyncPlayerChatEvent.setFormat(AsyncPlayerChatEvent.java:105) ~[pufferfish-api-1.18.2-R0.1-SNAPSHOT.jar:?]
        at ru.mrbrikster.chatty.chat.ChatListener.onChatMonitor(ChatListener.java:327) ~[Chatty.jar:?]
        at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor86.execute(Unknown Source) ~[?:?]
        at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:75) ~[pufferfish-api-1.18.2-R0.1-SNAPSHOT.jar:?]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:76) ~[pufferfish-api-1.18.2-R0.1-SNAPSHOT.jar:git-Pufferfish-56]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[pufferfish-api-1.18.2-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:631) ~[pufferfish-api-1.18.2-R0.1-SNAPSHOT.jar:?]
        at io.papermc.paper.adventure.ChatProcessor.post(ChatProcessor.java:194) ~[pufferfish-1.18.2.jar:git-Pufferfish-56]
        at io.papermc.paper.adventure.ChatProcessor.process(ChatProcessor.java:66) ~[pufferfish-1.18.2.jar:git-Pufferfish-56]
        at net.minecraft.server.network.ServerGamePacketListenerImpl.chat(ServerGamePacketListenerImpl.java:2224) ~[?:?]
        at net.minecraft.server.network.ServerGamePacketListenerImpl.handleChat(ServerGamePacketListenerImpl.java:2135) ~[?:?]
        at net.minecraft.server.network.ServerGamePacketListenerImpl.handleChat(ServerGamePacketListenerImpl.java:2101) ~[?:?]
        at net.minecraft.network.protocol.game.ServerboundChatPacket$1.run(ServerboundChatPacket.java:40) ~[?:?]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) ~[?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) ~[?:?]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]```

**Comment by Brikster** [comment]
В каких ситуациях возникает?

**Comment by SkyWatcher2019** [comment]
![image](https://user-images.githubusercontent.com/62600934/159355703-c25bbe3d-3d88-4801-bde6-254f4d443f03.png)
![image](https://user-images.githubusercontent.com/62600934/159355718-4aa68655-a796-4d9c-8dd3-e51c3dd61206.png)
Если написать % в сообщении
