### ISSUE TITLE
Error /sudo 

### ISSUE THREAD

**Issue by 1Pootis1** [Brikster/Chatty#168]
[18:34:30] [Server thread/INFO]: KevstaRU issued server command: /sudo NeNazvali c:1
[18:34:30] [Server thread/ERROR]: Could not pass event AsyncPlayerChatEvent to Chatty v2.19.5
java.lang.IllegalStateException: ChattyMessageEvent may only be triggered asynchronously.
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:614) ~[patched_1.17.1.jar:git-Paper-409]
	at ru.mrbrikster.chatty.chat.ChatListener.onChat(ChatListener.java:196) ~[Chatty.jar:?]
	at ru.mrbrikster.chatty.chat.ChatListener.execute(ChatListener.java:94) ~[Chatty.jar:?]
	at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[patched_1.17.1.jar:git-Paper-409]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[patched_1.17.1.jar:git-Paper-409]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:628) ~[patched_1.17.1.jar:git-Paper-409]
	at io.papermc.paper.adventure.ChatProcessor.post(ChatProcessor.java:230) ~[patched_1.17.1.jar:git-Paper-409]
	at io.papermc.paper.adventure.ChatProcessor.processingLegacyFirst(ChatProcessor.java:115) ~[patched_1.17.1.jar:git-Paper-409]
	at io.papermc.paper.adventure.ChatProcessor.process(ChatProcessor.java:64) ~[patched_1.17.1.jar:git-Paper-409]
	at net.minecraft.server.network.ServerGamePacketListenerImpl.chat(ServerGamePacketListenerImpl.java:2179) ~[app:?]
	at org.bukkit.craftbukkit.v1_17_R1.entity.CraftPlayer.chat(CraftPlayer.java:642) ~[patched_1.17.1.jar:git-Paper-409]
	at com.earth2me.essentials.commands.Commandsudo.updatePlayer(Commandsudo.java:41) ~[EssentialsX-2.19.4.jar:?]
	at com.earth2me.essentials.commands.EssentialsLoopCommand.lambda$loopOnlinePlayers$1(EssentialsLoopCommand.java:67) ~[EssentialsX-2.19.4.jar:?]
	at com.earth2me.essentials.commands.EssentialsLoopCommand.loopOnlinePlayersConsumer(EssentialsLoopCommand.java:118) ~[EssentialsX-2.19.4.jar:?]
	at com.earth2me.essentials.commands.EssentialsLoopCommand.loopOnlinePlayers(EssentialsLoopCommand.java:67) ~[EssentialsX-2.19.4.jar:?]
	at com.earth2me.essentials.commands.Commandsudo.run(Commandsudo.java:26) ~[EssentialsX-2.19.4.jar:?]
	at com.earth2me.essentials.commands.EssentialsCommand.run(EssentialsCommand.java:177) ~[EssentialsX-2.19.4.jar:?]
	at com.earth2me.essentials.commands.EssentialsCommand.run(EssentialsCommand.java:172) ~[EssentialsX-2.19.4.jar:?]
	at com.earth2me.essentials.Essentials.onCommandEssentials(Essentials.java:797) ~[EssentialsX-2.19.4.jar:?]
	at com.earth2me.essentials.Essentials.onCommand(Essentials.java:700) ~[EssentialsX-2.19.4.jar:?]
	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45) ~[patched_1.17.1.jar:git-Paper-409]
	at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:159) ~[patched_1.17.1.jar:git-Paper-409]
	at org.bukkit.craftbukkit.v1_17_R1.CraftServer.dispatchCommand(CraftServer.java:869) ~[patched_1.17.1.jar:git-Paper-409]
	at net.minecraft.server.network.ServerGamePacketListenerImpl.handleCommand(ServerGamePacketListenerImpl.java:2262) ~[app:?]
	at net.minecraft.server.network.ServerGamePacketListenerImpl.handleChat(ServerGamePacketListenerImpl.java:2073) ~[app:?]
	at net.minecraft.server.network.ServerGamePacketListenerImpl.handleChat(ServerGamePacketListenerImpl.java:2054) ~[app:?]
	at net.minecraft.network.protocol.game.ServerboundChatPacket.handle(ServerboundChatPacket.java:46) ~[app:?]
	at net.minecraft.network.protocol.game.ServerboundChatPacket.a(ServerboundChatPacket.java:6) ~[app:?]
	at net.minecraft.network.protocol.PacketUtils.lambda$ensureRunningOnSameThread$1(PacketUtils.java:56) ~[app:?]
	at net.minecraft.server.TickTask.run(TickTask.java:18) ~[patched_1.17.1.jar:git-Paper-409]
	at net.minecraft.util.thread.BlockableEventLoop.doRunTask(BlockableEventLoop.java:149) ~[app:?]
	at net.minecraft.util.thread.ReentrantBlockableEventLoop.doRunTask(ReentrantBlockableEventLoop.java:23) ~[app:?]
	at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:1426) ~[patched_1.17.1.jar:git-Paper-409]
	at net.minecraft.server.MinecraftServer.executeTask(MinecraftServer.java:192) ~[patched_1.17.1.jar:git-Paper-409]
	at net.minecraft.util.thread.BlockableEventLoop.pollTask(BlockableEventLoop.java:122) ~[app:?]
	at net.minecraft.server.MinecraftServer.pollTaskInternal(MinecraftServer.java:1404) ~[patched_1.17.1.jar:git-Paper-409]
	at net.minecraft.server.MinecraftServer.pollTask(MinecraftServer.java:1397) ~[patched_1.17.1.jar:git-Paper-409]
	at net.minecraft.util.thread.BlockableEventLoop.managedBlock(BlockableEventLoop.java:132) ~[app:?]
	at net.minecraft.server.MinecraftServer.waitUntilNextTick(MinecraftServer.java:1375) ~[patched_1.17.1.jar:git-Paper-409]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1286) ~[patched_1.17.1.jar:git-Paper-409]
	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:319) ~[patched_1.17.1.jar:git-Paper-409]
	at java.lang.Thread.run(Thread.java:833) ~[?:?]

**Comment by Brikster** [comment]
![image](https://user-images.githubusercontent.com/11031798/166112570-5a9652b6-7fa0-49a1-8d95-e13171fcf1ab.png)
