### ISSUE TITLE
Ошибка при использовании json в автосообщениях на версии 1.16.5

### ISSUE THREAD

**Issue by DenaryDev** [Brikster/Chatty#176]
Ядро: последний билд purpur 1.16.5
Версия chatty: 2.9.11

```
[17:27:18 WARN]: [Chatty] Task #218 for Chatty v2.19.11 generated an exception
java.lang.RuntimeException: NMS features is not supported by Chatty on your server version (v1_16_R3)
        at ru.mrbrikster.chatty.util.textapi.NMSUtil.sendChatPacket(NMSUtil.java:157) ~[?:?]
        at ru.mrbrikster.chatty.notifications.ChatNotification.lambda$null$1(ChatNotification.java:72) ~[?:?]
        at java.util.ArrayList.forEach(ArrayList.java:1259) ~[?:1.8.0_301]
        at ru.mrbrikster.chatty.notifications.ChatNotification.lambda$run$2(ChatNotification.java:66) ~[?:?]
        at java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:184) ~[?:1.8.0_301]
        at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:175) ~[?:1.8.0_301]
        at java.util.Iterator.forEachRemaining(Iterator.java:116) ~[?:1.8.0_301]
        at java.util.Spliterators$IteratorSpliterator.forEachRemaining(Spliterators.java:1801) ~[?:1.8.0_301]
        at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:482) ~[?:1.8.0_301]
        at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:472) ~[?:1.8.0_301]
        at java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:151) ~[?:1.8.0_301]
        at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:174) ~[?:1.8.0_301]
        at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234) ~[?:1.8.0_301]
        at java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:418) ~[?:1.8.0_301]
        at ru.mrbrikster.chatty.notifications.ChatNotification.run(ChatNotification.java:66) ~[?:?]
        at org.bukkit.craftbukkit.v1_16_R3.scheduler.CraftTask.run(CraftTask.java:100) ~[patched_1.16.5.jar:git-Purpur-1171]
        at org.bukkit.craftbukkit.v1_16_R3.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:468) ~[patched_1.16.5.jar:git-Purpur-1171]
        at net.minecraft.server.v1_16_R3.MinecraftServer.b(MinecraftServer.java:1503) ~[patched_1.16.5.jar:git-Purpur-1171]
        at net.minecraft.server.v1_16_R3.DedicatedServer.b(DedicatedServer.java:449) ~[patched_1.16.5.jar:git-Purpur-1171]
        at net.minecraft.server.v1_16_R3.MinecraftServer.a(MinecraftServer.java:1416) ~[patched_1.16.5.jar:git-Purpur-1171]
        at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:1142) ~[patched_1.16.5.jar:git-Purpur-1171]
        at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$a$0(MinecraftServer.java:293) ~[patched_1.16.5.jar:git-Purpur-1171]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_301]
Caused by: java.lang.IllegalStateException
        at ru.mrbrikster.chatty.util.textapi.NMSUtil.sendChatPacket(NMSUtil.java:109) ~[?:?]
        ... 22 more
```

**Comment by dimadencep** [comment]
Какое ядро ты используешь?

**Comment by Brikster** [comment]
Будет исправлено в версии 3.0.
