### ISSUE TITLE
Ошибка при входе игрока на баккит-сервер.

### ISSUE THREAD

**Issue by itzJOHv** [Brikster/Chatty#179]
Есть 5 серверов:
- банжа (waterfall 1.19 497 билд)
- 4 баккит-сервера:
```
[12:50:22 INFO]: This server is running Mirai version git-Mirai-bc7c5ca (MC: 1.18.2) (Implementing API version 1.18.2-R0.1-SNAPSHOT) (Git: bc7c5ca on ver/1.18.2)
```

При входе игрока на любой **пустой** баккит-сервер, в консоль этого сервера вылазит ошибка:
```
[12:17:13 WARN]: [Chatty] Plugin Chatty v2.19.11 generated an exception whilst handling plugin message
java.lang.NullPointerException: Cannot invoke "ru.mrbrikster.chatty.shaded.gson.JsonArray.iterator()" because "extra" is null
        at ru.mrbrikster.chatty.json.fanciful.FancyMessage.deserialize(FancyMessage.java:103) ~[Chatty.jar:?]
        at ru.mrbrikster.chatty.json.fanciful.FancyMessage.deserialize(FancyMessage.java:142) ~[Chatty.jar:?]
        at ru.mrbrikster.chatty.bungee.BungeeCordListener.onPluginMessageReceived(BungeeCordListener.java:76) ~[Chatty.jar:?]
        at org.bukkit.plugin.messaging.StandardMessenger.dispatchIncomingMessage(StandardMessenger.java:455) ~[mirai-api-1.18.2-R0.1-SNAPSHOT.jar:?]
        at net.minecraft.server.network.ServerGamePacketListenerImpl.handleCustomPayload(ServerGamePacketListenerImpl.java:3253) ~[?:?]
        at net.minecraft.network.protocol.game.ServerboundCustomPayloadPacket.handle(ServerboundCustomPayloadPacket.java:37) ~[?:?]
        at net.minecraft.network.protocol.game.ServerboundCustomPayloadPacket.handle(ServerboundCustomPayloadPacket.java:15) ~[?:?]
        at net.minecraft.network.protocol.PacketUtils.lambda$ensureRunningOnSameThread$1(PacketUtils.java:51) ~[?:?]
        at net.minecraft.util.thread.BlockableEventLoop.doRunTask(BlockableEventLoop.java:168) ~[?:?]
        at net.minecraft.util.thread.ReentrantBlockableEventLoop.doRunTask(ReentrantBlockableEventLoop.java:24) ~[?:?]
        at net.minecraft.util.thread.BlockableEventLoop.pollTask(BlockableEventLoop.java:130) ~[?:?]
        at net.minecraft.server.MinecraftServer.pollTaskInternal(MinecraftServer.java:1391) ~[mirai-1.18.2.jar:git-Mirai-bc7c5ca]
        at net.minecraft.server.MinecraftServer.pollTask(MinecraftServer.java:1384) ~[mirai-1.18.2.jar:git-Mirai-bc7c5ca]
        at net.minecraft.util.thread.BlockableEventLoop.managedBlock(BlockableEventLoop.java:141) ~[?:?]
        at net.minecraft.server.MinecraftServer.waitUntilNextTick(MinecraftServer.java:1360) ~[mirai-1.18.2.jar:git-Mirai-bc7c5ca]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1242) ~[mirai-1.18.2.jar:git-Mirai-bc7c5ca]
        at net.minecraft.server.MinecraftServer.lambda$spin$1(MinecraftServer.java:318) ~[mirai-1.18.2.jar:git-Mirai-bc7c5ca]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]
```

**Comment by Brikster** [comment]
Будет исправлено в новой версии 3.0.
