### ISSUE TITLE
🪲Баг: no valid sound name for BLOCK_RESPAWN_ANCHOR_CHARGE

### ISSUE THREAD

**Issue by lynrayy** [Brikster/Chatty#210]
Плагин не понимает звук BLOCK_RESPAWN_ANCHOR_CHARGE, который есть в списке звуков баккит
![image](https://user-images.githubusercontent.com/59417884/205457404-cb3b5c18-d40a-4e31-9195-39a1fdee61ad.png)

`[21:57:35 ERROR]: Could not pass event PlayerJoinEvent to Chatty v2.19.12
java.lang.IllegalArgumentException: Found no valid sound name for BLOCK_RESPAWN_ANCHOR_CHARGE
        at ru.mrbrikster.chatty.util.Sound.byName(Sound.java:217) ~[Chatty.jar:?]
        at ru.mrbrikster.chatty.miscellaneous.MiscellaneousListener.onJoin(MiscellaneousListener.java:76) ~[Chatty.jar:?]
        at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor83.execute(Unknown Source) ~[?:?]
        at org.bukkit.plugin.EventExecutor$2.execute(EventExecutor.java:77) ~[paper-api-1.19.2-R0.1-SNAPSHOT.jar:?]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[paper-api-1.19.2-R0.1-SNAPSHOT.jar:git-Paper-302]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[paper-api-1.19.2-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:670) ~[paper-api-1.19.2-R0.1-SNAPSHOT.jar:?]
        at net.minecraft.server.players.PlayerList.postChunkLoadJoin(PlayerList.java:372) ~[paper-1.19.2.jar:git-Paper-302]
        at net.minecraft.server.players.PlayerList.lambda$placeNewPlayer$0(PlayerList.java:309) ~[paper-1.19.2.jar:git-Paper-302]
        at net.minecraft.server.TickTask.run(TickTask.java:18) ~[paper-1.19.2.jar:git-Paper-302]
        at net.minecraft.util.thread.BlockableEventLoop.doRunTask(BlockableEventLoop.java:153) ~[?:?]
        at net.minecraft.util.thread.ReentrantBlockableEventLoop.doRunTask(ReentrantBlockableEventLoop.java:24) ~[?:?]
        at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:1341) ~[paper-1.19.2.jar:git-Paper-302]
        at net.minecraft.server.MinecraftServer.d(MinecraftServer.java:185) ~[paper-1.19.2.jar:git-Paper-302]
        at net.minecraft.util.thread.BlockableEventLoop.pollTask(BlockableEventLoop.java:126) ~[?:?]
        at net.minecraft.server.MinecraftServer.pollTaskInternal(MinecraftServer.java:1318) ~[paper-1.19.2.jar:git-Paper-302]
        at net.minecraft.server.MinecraftServer.pollTask(MinecraftServer.java:1311) ~[paper-1.19.2.jar:git-Paper-302]
        at net.minecraft.util.thread.BlockableEventLoop.managedBlock(BlockableEventLoop.java:136) ~[?:?]
        at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1389) ~[paper-1.19.2.jar:git-Paper-302]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1173) ~[paper-1.19.2.jar:git-Paper-302]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:305) ~[paper-1.19.2.jar:git-Paper-302]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]
[21:57:35 INFO]: + ⛏ Lynrayy`

**Comment by lynrayy** [comment]
![image](https://user-images.githubusercontent.com/59417884/205457445-922dbf6a-b644-4179-b412-369f8f0723a2.png)

**Comment by lynrayy** [comment]
Сейчас выяснилось, что UI_TOAST_CHALLENGE_COMPLETE тоже не работает
В то же время, если вписать туда же ENTITY_VILLAGER_NO, то звук есть

**Comment by lynrayy** [comment]
Да что за ужас, плагин под 1.12 писался что ли? 
java.lang.IllegalArgumentException: Found no valid sound name for BLOCK_FENCE_GATE_OPEN
