### ISSUE TITLE
Error from Console

### ISSUE THREAD

**Issue by Sm1leClock** [Brikster/Chatty#211]
[15:22:42 ERROR]: Could not pass event AsyncPlayerChatEvent to Chatty v2.19.12
ru.mrbrikster.chatty.shaded.gson.JsonSyntaxException: java.io.EOFException: End of input at line 1 column 23647 path $.last-pm-interlocutor.NyShyaFiNik
        at ru.mrbrikster.chatty.shaded.gson.internal.Streams.parse(Streams.java:58) ~[?:?]
        at ru.mrbrikster.chatty.shaded.gson.JsonParser.parseReader(JsonParser.java:85) ~[?:?]
        at ru.mrbrikster.chatty.shaded.gson.JsonParser.parseReader(JsonParser.java:60) ~[?:?]
        at ru.mrbrikster.chatty.shaded.gson.JsonParser.parseString(JsonParser.java:47) ~[?:?]
        at ru.mrbrikster.chatty.shaded.gson.JsonParser.parse(JsonParser.java:98) ~[?:?]
        at ru.mrbrikster.chatty.chat.JsonStorage.getProperty(JsonStorage.java:81) ~[?:?]
        at ru.mrbrikster.chatty.chat.JsonStorage.getProperty(JsonStorage.java:109) ~[?:?]
        at ru.mrbrikster.chatty.chat.Chat.lambda$filterRecipients$1(Chat.java:101) ~[?:?]
        at java.util.Collection.removeIf(Collection.java:576) ~[?:?]
        at ru.mrbrikster.chatty.chat.Chat.filterRecipients(Chat.java:99) ~[?:?]
        at ru.mrbrikster.chatty.chat.ChatListener.onChat(ChatListener.java:162) ~[?:?]
        at ru.mrbrikster.chatty.chat.ChatListener.execute(ChatListener.java:95) ~[?:?]
        at co.aikar.timings.TimedEventExecutor.execute(:76) ~[server.jar:git-Airplane-"3fbf522"]
        at org.bukkit.plugin.RegisteredListener.callEvent(:70) ~[server.jar:git-Airplane-"3fbf522"]
        at org.bukkit.plugin.SimplePluginManager.callEvent(:624) ~[server.jar:git-Airplane-"3fbf522"]
        at io.papermc.paper.adventure.ChatProcessor.post(:225) ~[server.jar:git-Airplane-"3fbf522"]
        at io.papermc.paper.adventure.ChatProcessor.processingLegacyFirst(:107) ~[server.jar:git-Airplane-"3fbf522"]
        at io.papermc.paper.adventure.ChatProcessor.process(:65) ~[server.jar:git-Airplane-"3fbf522"]
        at net.minecraft.server.v1_16_R3.PlayerConnection.chat(:2216) ~[server.jar:git-Airplane-"3fbf522"]
        at net.minecraft.server.v1_16_R3.PlayerConnection.c(:2131) ~[server.jar:git-Airplane-"3fbf522"]
        at net.minecraft.server.v1_16_R3.PlayerConnection.a(:2069) ~[server.jar:git-Airplane-"3fbf522"]
        at net.minecraft.server.v1_16_R3.PacketPlayInChat$1.run(:43) ~[server.jar:git-Airplane-"3fbf522"]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515) ~[?:?]
        at java.util.concurrent.FutureTask.run(FutureTask.java:264) ~[?:?]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130) [?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630) [?:?]
        at java.lang.Thread.run(Thread.java:831) [?:?]
Caused by: java.io.EOFException: End of input at line 1 column 23647 path $.last-pm-interlocutor.NyShyaFiNik
        at ru.mrbrikster.chatty.shaded.gson.stream.JsonReader.nextNonWhitespace(JsonReader.java:1395) ~[?:?]
        at ru.mrbrikster.chatty.shaded.gson.stream.JsonReader.doPeek(JsonReader.java:548) ~[?:?]
        at ru.mrbrikster.chatty.shaded.gson.stream.JsonReader.peek(JsonReader.java:424) ~[?:?]
        at ru.mrbrikster.chatty.shaded.gson.internal.bind.TypeAdapters$27.read(TypeAdapters.java:661) ~[?:?]
        at ru.mrbrikster.chatty.shaded.gson.internal.bind.TypeAdapters$27.read(TypeAdapters.java:684) ~[?:?]
        at ru.mrbrikster.chatty.shaded.gson.internal.bind.TypeAdapters$27.read(TypeAdapters.java:684) ~[?:?]
        at ru.mrbrikster.chatty.shaded.gson.internal.bind.TypeAdapters$27.read(TypeAdapters.java:655) ~[?:?]
        at ru.mrbrikster.chatty.shaded.gson.internal.Streams.parse(Streams.java:48) ~[?:?]
        ... 26 more

**Comment by F3F5** [comment]
+
