### ISSUE TITLE
1.5.2 support?

### ISSUE THREAD

**Issue by KweezyCode** [Brikster/Chatty#212]
java.lang.NoSuchMethodError: org.bukkit.configuration.file.YamlConfiguration.loadConfiguration(Ljava/io/Reader;)Lorg/bukkit/configuration/file/YamlConfiguration;
        at ru.mrbrikster.chatty.util.Messages.<init>(Messages.java:61)
        at ru.mrbrikster.chatty.Chatty.onEnable(Chatty.java:60)
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:217)
        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:457)
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:382)
        at org.bukkit.craftbukkit.v1_5_R3.CraftServer.loadPlugin(CraftServer.java:284)
        at org.bukkit.craftbukkit.v1_5_R3.CraftServer.enablePlugins(CraftServer.java:266)
        at net.minecraft.server.v1_5_R3.MinecraftServer.j(MinecraftServer.java:310)
        at net.minecraft.server.v1_5_R3.MinecraftServer.e(MinecraftServer.java:289)
        at net.minecraft.server.v1_5_R3.MinecraftServer.a(MinecraftServer.java:249)
        at net.minecraft.server.v1_5_R3.DedicatedServer.init(DedicatedServer.java:160)
        at net.minecraft.server.v1_5_R3.MinecraftServer.run(MinecraftServer.java:388)
        at net.minecraft.server.v1_5_R3.ThreadServerApplication.run(SourceFile:573)
        
1.5.2 is not supported anymore...?

**Comment by F3F5** [comment]
delete folder chatty and try again

**Comment by KweezyCode** [comment]
it is clean install, not working

**Comment by Brikster** [comment]
Sorry for misinformation at banner. 1.5.2 is not currently supported, try to use one of previous versions
