### ISSUE TITLE
1.20 console error

### ISSUE THREAD

**Issue by forditt** [Brikster/Chatty#232]
```
[21:16:20 ERROR]: Could not pass event AsyncPlayerChatEvent to Chatty v2.19.12
java.lang.RuntimeException: NMS features is not supported by Chatty on your server version (v1_20_R1)
        at ru.mrbrikster.chatty.util.textapi.NMSUtil.sendChatPacket(NMSUtil.java:173) ~[Chatty.jar:?]
        at ru.mrbrikster.chatty.json.fanciful.FancyMessage.send(FancyMessage.java:582) ~[Chatty.jar:?]
        at ru.mrbrikster.chatty.json.fanciful.FancyMessage.send(FancyMessage.java:607) ~[Chatty.jar:?]
        at ru.mrbrikster.chatty.json.FormattedMessage.send(FormattedMessage.java:30) ~[Chatty.jar:?]
        at ru.mrbrikster.chatty.chat.ChatListener.performJsonMessage(ChatListener.java:387) ~[Chatty.jar:?]
        at ru.mrbrikster.chatty.chat.ChatListener.onChatMonitor(ChatListener.java:330) ~[Chatty.jar:?]
        at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor43.execute(Unknown Source) ~[?:?]
        at org.bukkit.plugin.EventExecutor$2.execute(EventExecutor.java:77) ~[purpur-api-1.20-R0.1-SNAPSHOT.jar:?]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:77) ~[purpur-api-1.20-R0.1-SNAPSHOT.jar:git-Purpur-1986]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[purpur-api-1.20-R0.1-SNAPSHOT.jar:?]
        at io.papermc.paper.plugin.manager.PaperEventManager.callEvent(PaperEventManager.java:54) ~[purpur-1.20.jar:git-Purpur-1986]
        at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.callEvent(PaperPluginManagerImpl.java:126) ~[purpur-1.20.jar:git-Purpur-1986]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:615) ~[purpur-api-1.20-R0.1-SNAPSHOT.jar:?]
        at io.papermc.paper.adventure.ChatProcessor.post(ChatProcessor.java:414) ~[purpur-1.20.jar:git-Purpur-1986]
        at io.papermc.paper.adventure.ChatProcessor.process(ChatProcessor.java:100) ~[purpur-1.20.jar:git-Purpur-1986]
        at net.minecraft.server.network.ServerGamePacketListenerImpl.chat(ServerGamePacketListenerImpl.java:2492) ~[?:?]
        at net.minecraft.server.network.ServerGamePacketListenerImpl.broadcastChatMessage(ServerGamePacketListenerImpl.java:2648) ~[?:?]
        at net.minecraft.server.network.ServerGamePacketListenerImpl.lambda$handleChat$18(ServerGamePacketListenerImpl.java:2321) ~[?:?]
        at java.util.concurrent.CompletableFuture$UniAccept.tryFire(CompletableFuture.java:718) ~[?:?]
        at java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:482) ~[?:?]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) ~[?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) ~[?:?]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]
Caused by: java.lang.IllegalStateException
        at ru.mrbrikster.chatty.util.textapi.NMSUtil.resolveField(NMSUtil.java:77) ~[Chatty.jar:?]
        at ru.mrbrikster.chatty.util.textapi.NMSUtil.sendChatPacket(NMSUtil.java:87) ~[Chatty.jar:?]
```

**Comment by DimonKoT** [comment]
How did you fixed this?

**Comment by forditt** [comment]
> How did you fixed this?

I installed this version, which supports 1.20 - https://github.com/Brikster/Chatty/actions/runs/5300586096
