### ISSUE TITLE
Не работает ЛС на сервере 0_0

### ISSUE THREAD

**Issue by BKYCHblU-TOPTUK** [Brikster/Chatty#235]
Не работает функция ЛС у игроков!
Выдает такую ошибку
`[23:01:37 ERROR]: null
org.bukkit.command.CommandException: Unhandled exception executing 'pm NIKITOSIK_Last dasdasasd' in ru.mrbrikster.chatty.commands.pm.MsgCommand(msg)
        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:193) ~[SimpleCommandMap.class:1.7.10-5.4]
        at org.bukkit.craftbukkit.v1_7_R4.CraftServer.dispatchCommand(CraftServer.java:702) ~[CraftServer.class:1.7.10-5.4]
        at net.minecraft.network.NetHandlerPlayServer.func_147361_d(NetHandlerPlayServer.java:1381) [nh.class:?]
        at net.minecraft.network.NetHandlerPlayServer.func_147354_a(NetHandlerPlayServer.java:1118) [nh.class:?]
        at net.minecraft.network.play.client.C01PacketChatMessage.func_148833_a(C01PacketChatMessage.java:38) [ir.class:?]
        at net.minecraft.network.play.client.C01PacketChatMessage.func_148833_a(C01PacketChatMessage.java:53) [ir.class:?]
        at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:245) [ej.class:?]
        at net.minecraft.network.NetworkSystem.func_151269_c(NetworkSystem.java:181) [nc.class:?]
        at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:1023) [MinecraftServer.class:?]
        at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:431) [lt.class:?]
        at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:842) [MinecraftServer.class:?]
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:692) [MinecraftServer.class:?]
        at java.lang.Thread.run(Thread.java:750) [?:1.8.0_372]
Caused by: java.lang.NoClassDefFoundError: Could not initialize class ru.mrbrikster.chatty.util.textapi.NMSUtil
        at ru.mrbrikster.chatty.json.fanciful.FancyMessage.send(FancyMessage.java:582) ~[?:?]
        at ru.mrbrikster.chatty.json.fanciful.FancyMessage.send(FancyMessage.java:573) ~[?:?]
        at ru.mrbrikster.chatty.commands.pm.PrivateMessageCommand.handlePrivateMessage(PrivateMessageCommand.java:123) ~[?:?]
        at ru.mrbrikster.chatty.commands.pm.MsgCommand.handle(MsgCommand.java:62) ~[?:?]
        at ru.mrbrikster.chatty.shaded.baseplugin.commands.BukkitCommand.execute(BukkitCommand.java:47) ~[?:?]
        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:188) ~[SimpleCommandMap.class:1.7.10-5.4]
        ... 12 more`

**Comment by StKillReal** [comment]
![image](https://github.com/Brikster/Chatty/assets/60330193/471601eb-d982-43bb-891c-842b94bae6d3)
yep
