### ISSUE TITLE
Does not work /msg(also its aliases) | Не работает /msg(также его алиасы)

### ISSUE THREAD

**Issue by xyzrxltxhh** [Brikster/Chatty#238]
Ошибка в майнкрафте: ``` An internal error occurred while attempting to perform this command ```
A mistake in minecraft: ``` An internal error occurred while attempting to perform this command ```

```
[00:56:24 INFO]: xyzrxltxh issued server command: /pm xddtester 123
[00:56:24 ERROR]: null
org.bukkit.command.CommandException: Unhandled exception executing 'pm xddtester 123' in ru.mrbrikster.chatty.commands.pm.MsgCommand(msg)
        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:165) ~[paper-api-1.20.1-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.craftbukkit.v1_20_R1.CraftServer.dispatchCommand(CraftServer.java:1006) ~[paper-1.20.1.jar:git-Paper-63]
        at org.bukkit.craftbukkit.v1_20_R1.command.BukkitCommandWrapper.run(BukkitCommandWrapper.java:64) ~[paper-1.20.1.jar:git-Paper-63]
        at com.mojang.brigadier.CommandDispatcher.execute(CommandDispatcher.java:265) ~[paper-1.20.1.jar:?]
        at net.minecraft.commands.Commands.performCommand(Commands.java:324) ~[?:?]
        at net.minecraft.commands.Commands.performCommand(Commands.java:308) ~[?:?]
        at net.minecraft.server.network.ServerGamePacketListenerImpl.performChatCommand(ServerGamePacketListenerImpl.java:2299) ~[?:?]
        at net.minecraft.server.network.ServerGamePacketListenerImpl.lambda$handleChatCommand$20(ServerGamePacketListenerImpl.java:2259) ~[?:?]
        at net.minecraft.util.thread.BlockableEventLoop.lambda$submitAsync$0(BlockableEventLoop.java:59) ~[?:?]
        at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1768) ~[?:?]
        at net.minecraft.server.TickTask.run(TickTask.java:18) ~[paper-1.20.1.jar:git-Paper-63]
        at net.minecraft.util.thread.BlockableEventLoop.doRunTask(BlockableEventLoop.java:153) ~[?:?]
        at net.minecraft.util.thread.ReentrantBlockableEventLoop.doRunTask(ReentrantBlockableEventLoop.java:24) ~[?:?]
        at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:1339) ~[paper-1.20.1.jar:git-Paper-63]
        at net.minecraft.server.MinecraftServer.d(MinecraftServer.java:197) ~[paper-1.20.1.jar:git-Paper-63]
        at net.minecraft.util.thread.BlockableEventLoop.pollTask(BlockableEventLoop.java:126) ~[?:?]
        at net.minecraft.server.MinecraftServer.pollTaskInternal(MinecraftServer.java:1316) ~[paper-1.20.1.jar:git-Paper-63]
        at net.minecraft.server.MinecraftServer.pollTask(MinecraftServer.java:1309) ~[paper-1.20.1.jar:git-Paper-63]
        at net.minecraft.util.thread.BlockableEventLoop.runAllTasks(BlockableEventLoop.java:114) ~[?:?]
        at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1425) ~[paper-1.20.1.jar:git-Paper-63]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1171) ~[paper-1.20.1.jar:git-Paper-63]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:318) ~[paper-1.20.1.jar:git-Paper-63]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]
Caused by: java.lang.RuntimeException: NMS features is not supported by Chatty on your server version (v1_20_R1)
        at ru.mrbrikster.chatty.util.textapi.NMSUtil.sendChatPacket(NMSUtil.java:173) ~[Chatty.jar:?]
        at ru.mrbrikster.chatty.json.fanciful.FancyMessage.send(FancyMessage.java:582) ~[Chatty.jar:?]
        at ru.mrbrikster.chatty.json.fanciful.FancyMessage.send(FancyMessage.java:573) ~[Chatty.jar:?]
        at ru.mrbrikster.chatty.commands.pm.PrivateMessageCommand.handlePrivateMessage(PrivateMessageCommand.java:123) ~[Chatty.jar:?]
        at ru.mrbrikster.chatty.commands.pm.MsgCommand.handle(MsgCommand.java:62) ~[Chatty.jar:?]
        at ru.mrbrikster.chatty.shaded.baseplugin.commands.BukkitCommand.execute(BukkitCommand.java:47) ~[Chatty.jar:?]
        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:155) ~[paper-api-1.20.1-R0.1-SNAPSHOT.jar:?]
        ... 22 more
Caused by: java.lang.IllegalStateException
        at ru.mrbrikster.chatty.util.textapi.NMSUtil.resolveField(NMSUtil.java:77) ~[Chatty.jar:?]
        at ru.mrbrikster.chatty.util.textapi.NMSUtil.sendChatPacket(NMSUtil.java:87) ~[Chatty.jar:?]
        at ru.mrbrikster.chatty.json.fanciful.FancyMessage.send(FancyMessage.java:582) ~[Chatty.jar:?]
        at ru.mrbrikster.chatty.json.fanciful.FancyMessage.send(FancyMessage.java:573) ~[Chatty.jar:?]
        at ru.mrbrikster.chatty.commands.pm.PrivateMessageCommand.handlePrivateMessage(PrivateMessageCommand.java:123) ~[Chatty.jar:?]
        at ru.mrbrikster.chatty.commands.pm.MsgCommand.handle(MsgCommand.java:62) ~[Chatty.jar:?]
        at ru.mrbrikster.chatty.shaded.baseplugin.commands.BukkitCommand.execute(BukkitCommand.java:47) ~[Chatty.jar:?]
        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:155) ~[paper-api-1.20.1-R0.1-SNAPSHOT.jar:?]
        ... 22 more
```

**Comment by DINNKA** [comment]
через год обновит, привыкай

**Comment by DenaryDev** [comment]
Скачай отсюда, у меня работает https://github.com/Brikster/Chatty/suites/13704207405/artifacts/757747198

**Comment by xyzrxltxhh** [comment]
Спасибо заработало.

**Comment by xyzrxltxhh** [comment]
> Скачай отсюда, у меня работает https://github.com/Brikster/Chatty/suites/13704207405/artifacts/757747198

Спасибо, а что за версия плагина?

**Comment by xyzrxltxhh** [comment]
> Скачай отсюда, у меня работает https://github.com/Brikster/Chatty/suites/13704207405/artifacts/757747198

А как вы узнали?
