### ISSUE TITLE
[v3] /op игроки не могут писать в чат

### ISSUE THREAD

**Issue by AcidSoap** [Brikster/Chatty#268]
Шаги для воспроизведения бага
1. Запустить сервер spigot 1.17.1
2.Прописать /op на игрока
3. Написать что-нибудь в чат
4. Наблюдать ошибку в консоле.

[19:15:16] [Async Chat Thread - #0/ERROR]: Cannot handle chat event
java.lang.NoSuchMethodError: 'boolean java.util.regex.Matcher.hasMatch()'
        at ru.brikster.chatty.chat.message.transform.stage.post.MentionsTransformStrategy.handle(MentionsTransformStrategy.java:71) ~[Chatty-3.0.0-SNAPSHOT.jar:?]
        at ru.brikster.chatty.chat.message.transform.processor.MessageTransformStrategiesProcessorImpl.handle(MessageTransformStrategiesProcessorImpl.java:43) ~[Chatty-3.0.0-SNAPSHOT.jar:?]
        at ru.brikster.chatty.chat.executor.LegacyEventExecutor.sendProcessedMessage(LegacyEventExecutor.java:263) ~[Chatty-3.0.0-SNAPSHOT.jar:?]
        at ru.brikster.chatty.chat.executor.LegacyEventExecutor.handleFinishedEarlyContextEvent(LegacyEventExecutor.java:146) [Chatty-3.0.0-SNAPSHOT.jar:?]
        at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
        at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?]
        at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
        at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?]
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:306) [spigot-1.17.1-empty.jar:3284a-Spigot-3892929-0ab8487]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) [spigot-1.17.1-empty.jar:3284a-Spigot-3892929-0ab8487]
        at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:589) [spigot-1.17.1-empty.jar:3284a-Spigot-3892929-0ab8487]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:576) [spigot-1.17.1-empty.jar:3284a-Spigot-3892929-0ab8487]
        at net.minecraft.server.network.PlayerConnection.chat(PlayerConnection.java:1853) [spigot-1.17.1-empty.jar:3284a-Spigot-3892929-0ab8487]
        at net.minecraft.server.network.PlayerConnection.a(PlayerConnection.java:1787) [spigot-1.17.1-empty.jar:3284a-Spigot-3892929-0ab8487]
        at net.minecraft.server.network.PlayerConnection.a(PlayerConnection.java:1753) [spigot-1.17.1-empty.jar:3284a-Spigot-3892929-0ab8487]
        at net.minecraft.network.protocol.game.PacketPlayInChat$1.run(PacketPlayInChat.java:40) [spigot-1.17.1-empty.jar:3284a-Spigot-3892929-0ab8487]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539) [?:?]
        at java.util.concurrent.FutureTask.run(FutureTask.java:264) [?:?]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) [?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) [?:?]
        at java.lang.Thread.run(Thread.java:842) [?:?]
        
Для наглядности настройки файла chats.yml сброшены до дефолтных. Конфликты плагинов исключены, был лишь 1 плагин.

**Comment by Brikster** [comment]
Исправлено в [0c5f2d1](https://github.com/Brikster/Chatty/commit/0c5f2d151241fd1414dadc4e66d4ab727daf7f7e).
Ошибка связана с использованием метода, который доступен только в Java 20 и выше. Исправление позволяет запускать плагин на сервере с Java 11+.

Загрузить новую версию можно [здесь](https://github.com/Brikster/Chatty/actions/runs/7106260842), в разделе Artifacts.
