### ISSUE TITLE
error on start

### ISSUE THREAD

**Issue by ghost** [Brikster/Chatty#284]
[18:32:17 ERROR]: Error occurred while enabling Chatty v3.0.0-SNAPSHOT (Is it up to date?)
java.lang.NullPointerException: Execution handler may not be null
	at java.base/java.util.Objects.requireNonNull(Objects.java:235) ~[?:?]
	at Chatty-3.0.0-SNAPSHOT.jar/ru.brikster.chatty.shaded.cloud.commandframework.Command$Builder.<init>(Command.java:473) ~[Chatty-3.0.0-SNAPSHOT.jar:?]
	at Chatty-3.0.0-SNAPSHOT.jar/ru.brikster.chatty.shaded.cloud.commandframework.Command$Builder.handler(Command.java:1069) ~[Chatty-3.0.0-SNAPSHOT.jar:?]
	at Chatty-3.0.0-SNAPSHOT.jar/ru.brikster.chatty.Chatty.registerPmCommands(Chatty.java:298) ~[Chatty-3.0.0-SNAPSHOT.jar:?]
	at Chatty-3.0.0-SNAPSHOT.jar/ru.brikster.chatty.Chatty.initialize(Chatty.java:196) ~[Chatty-3.0.0-SNAPSHOT.jar:?]
	at Chatty-3.0.0-SNAPSHOT.jar/ru.brikster.chatty.Chatty.onEnable(Chatty.java:89) ~[Chatty-3.0.0-SNAPSHOT.jar:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:287) ~[leaf-api-1.20.4-R0.1-SNAPSHOT.jar:?]
	at io.papermc.paper.plugin.manager.PaperPluginInstanceManager.enablePlugin(PaperPluginInstanceManager.java:188) ~[leaf-1.20.4.jar:git-Leaf-"a5953c0"]
	at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.enablePlugin(PaperPluginManagerImpl.java:104) ~[leaf-1.20.4.jar:git-Leaf-"a5953c0"]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:506) ~[leaf-api-1.20.4-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.craftbukkit.v1_20_R3.CraftServer.enablePlugin(CraftServer.java:657) ~[leaf-1.20.4.jar:git-Leaf-"a5953c0"]
	at org.bukkit.craftbukkit.v1_20_R3.CraftServer.enablePlugins(CraftServer.java:568) ~[leaf-1.20.4.jar:git-Leaf-"a5953c0"]
	at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:657) ~[leaf-1.20.4.jar:git-Leaf-"a5953c0"]
	at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:417) ~[leaf-1.20.4.jar:git-Leaf-"a5953c0"]
	at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:354) ~[leaf-1.20.4.jar:git-Leaf-"a5953c0"]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1136) ~[leaf-1.20.4.jar:git-Leaf-"a5953c0"]
	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:306) ~[leaf-1.20.4.jar:git-Leaf-"a5953c0"]
	at java.base/java.lang.Thread.run(Thread.java:840) ~[?:?]
[18:32:17 INFO]: [Chatty] Disabling Chatty v3.0.0-SNAPSHOT
[18:32:17 ERROR]: Error occurred while disabling Chatty v3.0.0-SNAPSHOT
java.lang.NullPointerException: Cannot invoke "ru.brikster.chatty.shaded.cloud.commandframework.bukkit.BukkitCommandManager.commandTree()" because "commandManager" is null
	at Chatty-3.0.0-SNAPSHOT.jar/ru.brikster.chatty.Chatty.unregisterAllCommands(Chatty.java:336) ~[Chatty-3.0.0-SNAPSHOT.jar:?]
	at Chatty-3.0.0-SNAPSHOT.jar/ru.brikster.chatty.Chatty.onDisable(Chatty.java:326) ~[Chatty-3.0.0-SNAPSHOT.jar:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:290) ~[leaf-api-1.20.4-R0.1-SNAPSHOT.jar:?]
	at io.papermc.paper.plugin.manager.PaperPluginInstanceManager.disablePlugin(PaperPluginInstanceManager.java:223) ~[leaf-1.20.4.jar:git-Leaf-"a5953c0"]
	at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.disablePlugin(PaperPluginManagerImpl.java:109) ~[leaf-1.20.4.jar:git-Leaf-"a5953c0"]
	at org.bukkit.plugin.SimplePluginManager.disablePlugin(SimplePluginManager.java:536) ~[leaf-api-1.20.4-R0.1-SNAPSHOT.jar:?]
	at io.papermc.paper.plugin.manager.PaperPluginInstanceManager.enablePlugin(PaperPluginInstanceManager.java:192) ~[leaf-1.20.4.jar:git-Leaf-"a5953c0"]
	at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.enablePlugin(PaperPluginManagerImpl.java:104) ~[leaf-1.20.4.jar:git-Leaf-"a5953c0"]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:506) ~[leaf-api-1.20.4-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.craftbukkit.v1_20_R3.CraftServer.enablePlugin(CraftServer.java:657) ~[leaf-1.20.4.jar:git-Leaf-"a5953c0"]
	at org.bukkit.craftbukkit.v1_20_R3.CraftServer.enablePlugins(CraftServer.java:568) ~[leaf-1.20.4.jar:git-Leaf-"a5953c0"]
	at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:657) ~[leaf-1.20.4.jar:git-Leaf-"a5953c0"]
	at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:417) ~[leaf-1.20.4.jar:git-Leaf-"a5953c0"]
	at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:354) ~[leaf-1.20.4.jar:git-Leaf-"a5953c0"]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1136) ~[leaf-1.20.4.jar:git-Leaf-"a5953c0"]
	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:306) ~[leaf-1.20.4.jar:git-Leaf-"a5953c0"]
	at java.base/java.lang.Thread.run(Thread.java:840) ~[?:?]

**Comment by ghost** [comment]
fixed on enable pm.
