### ISSUE TITLE
На 1.20.6 периодически выскакивают ошибки 

### ISSUE THREAD

**Issue by PukPukov** [Brikster/Chatty#292]
```
[22:32:53 WARN]: [Chatty] Task #35 for Chatty v2.19.14 generated an exception
java.lang.RuntimeException: Titles are not supported by Chatty on your server version (v1_20_R4)
        at Chatty.jar/ru.mrbrikster.chatty.util.textapi.Title.send(Title.java:151) ~[Chatty.jar:?]
        at Chatty.jar/ru.mrbrikster.chatty.notifications.TitleNotification.lambda$run$1(TitleNotification.java:58) ~[Chatty.jar:?]
        at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:184) ~[?:?]
        at java.base/java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:194) ~[?:?]
        at java.base/java.util.AbstractList$RandomAccessSpliterator.forEachRemaining(AbstractList.java:722) ~[?:?]
        at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:556) ~[?:?]
        at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:546) ~[?:?]
        at java.base/java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:151) ~[?:?]
        at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:174) ~[?:?]
        at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:265) ~[?:?]
        at java.base/java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:611) ~[?:?]
        at Chatty.jar/ru.mrbrikster.chatty.notifications.TitleNotification.run(TitleNotification.java:44) ~[Chatty.jar:?]
        at org.bukkit.craftbukkit.scheduler.CraftTask.run(CraftTask.java:91) ~[?:?]
        at org.bukkit.craftbukkit.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:481) ~[?:?]
        at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1697) ~[leaf-1.20.6.jar:git-Leaf-"a46d325"]
        at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:515) ~[leaf-1.20.6.jar:git-Leaf-"a46d325"]        at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1579) ~[leaf-1.20.6.jar:git-Leaf-"a46d325"]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1241) ~[leaf-1.20.6.jar:git-Leaf-"a46d325"]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:315) ~[leaf-1.20.6.jar:git-Leaf-"a46d325"]
        at java.base/java.lang.Thread.run(Thread.java:1570) ~[?:?]
Caused by: java.lang.NoSuchMethodException: net.minecraft.network.chat.IChatBaseComponent$ChatSerializer.a(java.lang.String)
        at java.base/java.lang.Class.getMethod(Class.java:2405) ~[?:?]
        at Chatty.jar/ru.mrbrikster.chatty.util.textapi.Title.send(Title.java:94) ~[Chatty.jar:?]
        ... 19 more
```

**Comment by c1oudychan** [comment]
Установи Chatty v3 и жди пока обновят Adventure Kyori в нем.

**Comment by PukPukov** [comment]
Ок, оно, вроде, работает.
