### ISSUE TITLE
Bug on paper 1.21

### ISSUE THREAD

**Issue by KIRUYXAN** [Brikster/Chatty#302]
[19:05:47 WARN]: [Chatty] Task #12 for Chatty v2.19.14 generated an exception
java.lang.NoClassDefFoundError: Could not initialize class ru.mrbrikster.chatty.util.textapi.NMSUtil$ServerPackage
        at Chatty.jar/ru.mrbrikster.chatty.util.textapi.Title.send(Title.java:151) ~[Chatty.jar:?]
        at Chatty.jar/ru.mrbrikster.chatty.notifications.TitleNotification.lambda$run$1(TitleNotification.java:58) ~[Chatty.jar:?]
        at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:184) ~[?:?]
        at java.base/java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:179) ~[?:?]
        at java.base/java.util.AbstractList$RandomAccessSpliterator.forEachRemaining(AbstractList.java:722) ~[?:?]
        at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509) ~[?:?]
        at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499) ~[?:?]
        at java.base/java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:151) ~[?:?]
        at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:174) ~[?:?]
        at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234) ~[?:?]
        at java.base/java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:596) ~[?:?]
        at Chatty.jar/ru.mrbrikster.chatty.notifications.TitleNotification.run(TitleNotification.java:44) ~[Chatty.jar:?]
        at org.bukkit.craftbukkit.scheduler.CraftTask.run(CraftTask.java:101) ~[paper-1.21.jar:1.21-15-2df432f]
        at org.bukkit.craftbukkit.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:482) ~[paper-1.21.jar:1.21-15-2df432f]
        at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1654) ~[paper-1.21.jar:1.21-15-2df432f]
        at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:471) ~[paper-1.21.jar:1.21-15-2df432f]
        at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1538) ~[paper-1.21.jar:1.21-15-2df432f]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1246) ~[paper-1.21.jar:1.21-15-2df432f]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:329) ~[paper-1.21.jar:1.21-15-2df432f]
        at java.base/java.lang.Thread.run(Thread.java:1583) ~[?:?]
Caused by: java.lang.ExceptionInInitializerError: Exception java.lang.StringIndexOutOfBoundsException: Range [23, 22) out of bounds for length 22 [in thread "Server thread"]
        at java.base/jdk.internal.util.Preconditions$1.apply(Preconditions.java:55) ~[?:?]
        at java.base/jdk.internal.util.Preconditions$1.apply(Preconditions.java:52) ~[?:?]
        at java.base/jdk.internal.util.Preconditions$4.apply(Preconditions.java:213) ~[?:?]
        at java.base/jdk.internal.util.Preconditions$4.apply(Preconditions.java:210) ~[?:?]
        at java.base/jdk.internal.util.Preconditions.outOfBounds(Preconditions.java:98) ~[?:?]
        at java.base/jdk.internal.util.Preconditions.outOfBoundsCheckFromToIndex(Preconditions.java:112) ~[?:?]
        at java.base/jdk.internal.util.Preconditions.checkFromToIndex(Preconditions.java:349) ~[?:?]
        at java.base/java.lang.String.checkBoundsBeginEnd(String.java:4865) ~[?:?]
        at java.base/java.lang.String.substring(String.java:2834) ~[?:?]
        at java.base/java.lang.String.substring(String.java:2807) ~[?:?]
        at Chatty.jar/ru.mrbrikster.chatty.util.textapi.NMSUtil$ServerPackage.getServerVersion(NMSUtil.java:225) ~[Chatty.jar:?]
        at Chatty.jar/ru.mrbrikster.chatty.util.textapi.NMSUtil$ServerPackage.<clinit>(NMSUtil.java:215) ~[Chatty.jar:?]
        at Chatty.jar/ru.mrbrikster.chatty.util.textapi.NMSUtil.<clinit>(NMSUtil.java:22) ~[Chatty.jar:?]
        at Chatty.jar/ru.mrbrikster.chatty.util.textapi.Title.send(Title.java:86) ~[Chatty.jar:?]
        ... 19 more

**Comment by Brikster** [comment]
1.21 support implemented in f2417c12275f76f422c5a77b6b9859e65cffa35b.

**Comment by KIRUYXAN** [comment]
and how to download it to the server

**Comment by KIRUYXAN** [comment]
@Brikster

**Comment by KIRUYXAN** [comment]
Right now my server is crashing due to the same version of Chatty
