### ISSUE TITLE
Сервер крашится, когда любой игрок пишет команду /msg

### ISSUE THREAD

**Issue by chtko** [Brikster/Chatty#320]
Здравствуйте!
В плагине есть баг или ошибка, которая крашит сервер, когда кто-то из игроков пишет команду `/msg`. Права на использование команды у всех игроков есть.

## Логи:

```
[пт 19:14:30 ERROR Server] Encountered an unexpected exception
java.lang.NoClassDefFoundError: Could not initialize class ru.mrbrikster.chatty.util.textapi.NMSUtil
    at Chatty.jar//ru.mrbrikster.chatty.json.fanciful.FancyMessage.send(FancyMessage.java:582)
    at Chatty.jar//ru.mrbrikster.chatty.json.fanciful.FancyMessage.send(FancyMessage.java:594)
    at Chatty.jar//ru.mrbrikster.chatty.commands.pm.PrivateMessageCommand.handlePrivateMessage(PrivateMessageCommand.java:123)
    at Chatty.jar//ru.mrbrikster.chatty.commands.pm.MsgCommand.handle(MsgCommand.java:62)
    at Chatty.jar//ru.mrbrikster.chatty.shaded.baseplugin.commands.BukkitCommand.execute(BukkitCommand.java:47)
    at io.papermc.paper.command.brigadier.bukkit.BukkitCommandNode$BukkitBrigCommand.run(BukkitCommandNode.java:91)
    at com.mojang.brigadier.context.ContextChain.runExecutable(ContextChain.java:73)
    at net.minecraft.commands.execution.tasks.ExecuteCommand.execute(ExecuteCommand.java:31)
    at net.minecraft.commands.execution.tasks.ExecuteCommand.execute(ExecuteCommand.java:19)
    at net.minecraft.commands.execution.UnboundEntryAction.lambda$bind$0(UnboundEntryAction.java:8)
    at net.minecraft.commands.execution.CommandQueueEntry.execute(CommandQueueEntry.java:5)
    at net.minecraft.commands.execution.ExecutionContext.runCommandQueue(ExecutionContext.java:103)
    at net.minecraft.commands.Commands.executeCommandInContext(Commands.java:448)
    at net.minecraft.commands.Commands.performCommand(Commands.java:355)
    at net.minecraft.commands.Commands.performCommand(Commands.java:342)
    at net.minecraft.commands.Commands.performCommand(Commands.java:337)
    at net.minecraft.server.network.ServerGamePacketListenerImpl.performUnsignedChatCommand(ServerGamePacketListenerImpl.java:2202)
    at net.minecraft.server.network.ServerGamePacketListenerImpl.lambda$handleChatCommand$14(ServerGamePacketListenerImpl.java:2176)
    at net.minecraft.server.TickTask.run(TickTask.java:18)
    at net.minecraft.util.thread.
```
Надеюсь что ошибки из консоли помогут вам решить проблему с крашем сервера при вводе команды.

## Подробности
Ядро сервера: Paper
Версия: 1.20.6
ОС: Windows 10
Версия плагина: 2.19.14

**Comment by c1oudychan** [comment]
Попробуйте использовать Chatty v3. Chatty v2 устарел и не работает на новых версиях. Также в новой версии изменены конфиги полностью и используется [MiniMessage](https://docs.advntr.dev/minimessage/format.html).

Последний билд Chatty v3: https://github.com/Brikster/Chatty/actions/runs/9860012352

**Comment by chtko** [comment]
> Попробуйте использовать Chatty v3. Chatty v2 устарел и не работает на новых версиях. Также в новой версии изменены конфиги полностью и используется [MiniMessage](https://docs.advntr.dev/minimessage/format.html).
> 
> Последний билд Chatty v3: https://github.com/Brikster/Chatty/actions/runs/9860012352

Привет! Я не знал что есть разные версии Chatty. Попробую поставить на сервер V3 версию. 
Спасибо за ответ!

**Comment by moidar5366** [comment]
Здравствуйте, я написал тут, чтобы не создавать новый пост для этого, но когда я скачал эту версию плагина, то я не смог написать /msg без опки, какое тогда разрешение, если не chatty.command.msg? В плагине я не увидел

**Comment by chtko** [comment]
> Здравствуйте, я написал тут, чтобы не создавать новый пост для этого, но когда я скачал эту версию плагина, то я не смог написать /msg без опки, какое тогда разрешение, если не chatty.command.msg? В плагине я не увидел

Привет! Если вы имели в виду обычную версию плагина ([Release 2.19.14](https://github.com/Brikster/Chatty/releases/tag/v2.19.14)), то плагин [LuckPerms](https://www.spigotmc.org/resources/luckperms.28140/) в помощь.
А если вы имели в виду Chatty v3, то тут я вам уже не помогу...

_ _ _

Если вы используете обычную версию Chatty, то вы можете отключить `/msg`.
Отключить команду можно в файле:`config.yml`, вот тут (165 строка):
```commands:
    msg:
      # Enables "/msg" command.
      # Permission: chatty.command.msg
      enable: false
```
Советую перезагрузить сервер, чтобы командой управлял не Chatty, а сам Minecraft. Сразу скажу, что стиль у команды после перезагрузки будет обычный.

**Comment by moidar5366** [comment]
Увы, я использую V3, так как сервер на 1.21

**Comment by chtko** [comment]
> Увы, я использую V3, так как сервер на 1.21

Тогда ни чем не помогу:(

**Comment by Brikster** [comment]
> Здравствуйте, я написал тут, чтобы не создавать новый пост для этого, но когда я скачал эту версию плагина, то я не смог написать /msg без опки, какое тогда разрешение, если не chatty.command.msg? В плагине я не увидел

Список прав Chatty v3: [здесь](https://github.com/Brikster/Chatty/wiki/%D0%9A%D0%BE%D0%BC%D0%B0%D0%BD%D0%B4%D1%8B-%D0%B8-%D0%BF%D1%80%D0%B0%D0%B2%D0%B0). В новой версии на всю систему личных сообщений общее право.
