### ISSUE TITLE
oraxen эмодзи перестали работать

### ISSUE THREAD

**Issue by DropExitJoin** [Brikster/Chatty#332]
В последнем билде (до фикса прав на форматирование эмодзи работали) перестали работать эмодзи из oraxen (например "=)") в чате, сообщение не отправляется и получается ошибка:
```[23:36:18] [Async Chat Thread - #2/ERROR]: [ru.brikster.chatty.chat.executor.LegacyEventExecutor] Cannot handle chat event
ru.brikster.chatty.shaded.net.kyori.adventure.text.minimessage.internal.parser.ParsingExceptionImpl: Legacy formatting codes have been detected in a MiniMessage string - this is unsupported behaviour. Please refer to the Adventure documentation (https://docs.advntr.dev) for more information.
	§fꐢ
	^^
	at Chatty-3.0.0-SNAPSHOT.jar/ru.brikster.chatty.shaded.net.kyori.adventure.text.minimessage.internal.parser.TokenParser.parseString(TokenParser.java:170) ~[Chatty-3.0.0-SNAPSHOT.jar:?]
	at Chatty-3.0.0-SNAPSHOT.jar/ru.brikster.chatty.shaded.net.kyori.adventure.text.minimessage.internal.parser.TokenParser.resolvePreProcessTags(TokenParser.java:112) ~[Chatty-3.0.0-SNAPSHOT.jar:?]
	at Chatty-3.0.0-SNAPSHOT.jar/ru.brikster.chatty.shaded.net.kyori.adventure.text.minimessage.MiniMessageParser.parseToTree(MiniMessageParser.java:195) ~[Chatty-3.0.0-SNAPSHOT.jar:?]
	at Chatty-3.0.0-SNAPSHOT.jar/ru.brikster.chatty.shaded.net.kyori.adventure.text.minimessage.MiniMessageParser.parseFormat(MiniMessageParser.java:209) ~[Chatty-3.0.0-SNAPSHOT.jar:?]
	at Chatty-3.0.0-SNAPSHOT.jar/ru.brikster.chatty.shaded.net.kyori.adventure.text.minimessage.MiniMessageImpl.deserialize(MiniMessageImpl.java:80) ~[Chatty-3.0.0-SNAPSHOT.jar:?]
	at Chatty-3.0.0-SNAPSHOT.jar/ru.brikster.chatty.shaded.net.kyori.adventure.text.minimessage.MiniMessageImpl.deserialize(MiniMessageImpl.java:46) ~[Chatty-3.0.0-SNAPSHOT.jar:?]
	at Chatty-3.0.0-SNAPSHOT.jar/ru.brikster.chatty.chat.construct.ComponentFromContextConstructorImpl.construct(ComponentFromContextConstructorImpl.java:35) ~[Chatty-3.0.0-SNAPSHOT.jar:?]
	at Chatty-3.0.0-SNAPSHOT.jar/ru.brikster.chatty.chat.executor.LegacyEventExecutor.sendProcessedMessage(LegacyEventExecutor.java:356) ~[Chatty-3.0.0-SNAPSHOT.jar:?]
	at Chatty-3.0.0-SNAPSHOT.jar/ru.brikster.chatty.chat.executor.LegacyEventExecutor.handleFinishedEarlyContextEvent(LegacyEventExecutor.java:219) ~[Chatty-3.0.0-SNAPSHOT.jar:?]
	at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor264.execute(Unknown Source) ~[?:?]
	at org.bukkit.plugin.EventExecutor$2.execute(EventExecutor.java:77) ~[paper-mojangapi-1.21.1-R0.1-SNAPSHOT.jar:?]
	at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[paper-mojangapi-1.21.1-R0.1-SNAPSHOT.jar:1.21.1-2301-a43711d]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[paper-mojangapi-1.21.1-R0.1-SNAPSHOT.jar:?]
	at io.papermc.paper.plugin.manager.PaperEventManager.callEvent(PaperEventManager.java:54) ~[purpur-1.21.1.jar:1.21.1-2301-a43711d]
	at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.callEvent(PaperPluginManagerImpl.java:131) ~[purpur-1.21.1.jar:1.21.1-2301-a43711d]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:630) ~[paper-mojangapi-1.21.1-R0.1-SNAPSHOT.jar:?]
	at io.papermc.paper.adventure.ChatProcessor.post(ChatProcessor.java:378) ~[purpur-1.21.1.jar:1.21.1-2301-a43711d]
	at io.papermc.paper.adventure.ChatProcessor.process(ChatProcessor.java:85) ~[purpur-1.21.1.jar:1.21.1-2301-a43711d]
	at net.minecraft.server.network.ServerGamePacketListenerImpl.chat(ServerGamePacketListenerImpl.java:2485) ~[purpur-1.21.1.jar:1.21.1-2301-a43711d]
	at net.minecraft.server.network.ServerGamePacketListenerImpl.broadcastChatMessage(ServerGamePacketListenerImpl.java:2601) ~[purpur-1.21.1.jar:1.21.1-2301-a43711d]
	at net.minecraft.server.network.ServerGamePacketListenerImpl.lambda$handleChat$13(ServerGamePacketListenerImpl.java:2257) ~[purpur-1.21.1.jar:1.21.1-2301-a43711d]
	at net.minecraft.util.FutureChain.lambda$append$1(FutureChain.java:25) ~[purpur-1.21.1.jar:1.21.1-2301-a43711d]
	at java.base/java.util.concurrent.CompletableFuture$UniAccept.tryFire(CompletableFuture.java:718) ~[?:?]
	at java.base/java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:482) ~[?:?]
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144) ~[?:?]
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642) ~[?:?]
	at java.base/java.lang.Thread.run(Thread.java:1583) ~[?:?]```

**Comment by DropExitJoin** [comment]
Скок еще ждать?
