### ISSUE TITLE
error

### ISSUE THREAD

**Issue by DimaSergeew** [Brikster/Chatty#334]
[15:12:46 ERROR]: [ru.brikster.chatty.chat.executor.LegacyEventExecutor] Cannot handle chat event
ru.brikster.chatty.shaded.com.google.common.util.concurrent.UncheckedExecutionException: java.util.regex.PatternSyntaxException: Unclosed group near index 260
(?i)@§x§0§0§0§0§f§f§lL§x§1§2§0§0§e§d§lu§x§2§4§0§0§d§b§ls§x§3§7§0§0§c§8§lt§x§4§9§0§0§b§6§lf§x§5§b§0§0§a§4§lu§x§6§d§0§0§9§2§ll§x§8§0§0§0§8§0§l_§x§9§2§0§0§6§d§ll§x§a§4§0§0§5§b§lo§x§b§6§0§0§4§9§lv§x§c§8§0§0§3§7§le§x§d§b§0§0§2§4§l_§x§e§d§0§0§1§2§l(§x§f§f§0§0§0§0§l=
        at ru.brikster.chatty.shaded.com.google.common.cache.LocalCache$Segment.get(LocalCache.java:2051) ~[Chatty-3.0.0-SNAPSHOT.jar:?]
        at ru.brikster.chatty.shaded.com.google.common.cache.LocalCache.get(LocalCache.java:3951) ~[Chatty-3.0.0-SNAPSHOT.jar:?]
        at ru.brikster.chatty.shaded.com.google.common.cache.LocalCache$LocalManualCache.get(LocalCache.java:4848) ~[Chatty-3.0.0-SNAPSHOT.jar:?]
        at ru.brikster.chatty.chat.message.transform.stage.post.MentionsTransformStrategy.patternForPlayer(MentionsTransformStrategy.java:123) ~[Chatty-3.0.0-SNAPSHOT.jar:?]
        at ru.brikster.chatty.chat.message.transform.stage.post.MentionsTransformStrategy.handle(MentionsTransformStrategy.java:68) ~[Chatty-3.0.0-SNAPSHOT.jar:?]
        at ru.brikster.chatty.chat.message.transform.processor.MessageTransformStrategiesProcessorImpl.handle(MessageTransformStrategiesProcessorImpl.java:43) ~[Chatty-3.0.0-SNAPSHOT.jar:?]
        at ru.brikster.chatty.chat.executor.LegacyEventExecutor.sendProcessedMessage(LegacyEventExecutor.java:354) ~[Chatty-3.0.0-SNAPSHOT.jar:?]
        at ru.brikster.chatty.chat.executor.LegacyEventExecutor.handleFinishedEarlyContextEvent(LegacyEventExecutor.java:219) ~[Chatty-3.0.0-SNAPSHOT.jar:?]
        at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor1443.execute(Unknown Source) ~[?:?]
        at org.bukkit.plugin.EventExecutor$2.execute(EventExecutor.java:77) ~[?:git-UniverseSpigot-"3e1e308"]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:76) ~[?:git-UniverseSpigot-"3e1e308"]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[?:git-UniverseSpigot-"3e1e308"]
        at io.papermc.paper.plugin.manager.PaperEventManager.callEvent(PaperEventManager.java:76) ~[?:git-UniverseSpigot-"3e1e308"]
        at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.callEvent(PaperPluginManagerImpl.java:126) ~[?:git-UniverseSpigot-"3e1e308"]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:617) ~[?:git-UniverseSpigot-"3e1e308"]
        at io.papermc.paper.adventure.ChatProcessor.post(ChatProcessor.java:378) ~[?:git-UniverseSpigot-"3e1e308"]
        at io.papermc.paper.adventure.ChatProcessor.process(ChatProcessor.java:85) ~[?:git-UniverseSpigot-"3e1e308"]
        at net.minecraft.server.network.ServerGamePacketListenerImpl.chat(ServerGamePacketListenerImpl.java:2338) ~[?:?]
        at net.minecraft.server.network.ServerGamePacketListenerImpl.broadcastChatMessage(ServerGamePacketListenerImpl.java:2463) ~[?:?]
        at net.minecraft.server.network.ServerGamePacketListenerImpl.lambda$handleChat$13(ServerGamePacketListenerImpl.java:2187) ~[?:?]
        at net.minecraft.util.FutureChain.lambda$append$1(FutureChain.java:25) ~[?:git-UniverseSpigot-"3e1e308"]
        at java.util.concurrent.CompletableFuture$UniAccept.tryFire(CompletableFuture.java:718) ~[?:?]
        at java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:482) ~[?:?]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144) ~[?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642) ~[?:?]
        at java.lang.Thread.run(Thread.java:1583) ~[?:?]
Caused by: java.util.regex.PatternSyntaxException: Unclosed group near index 260
(?i)@§x§0§0§0§0§f§f§lL§x§1§2§0§0§e§d§lu§x§2§4§0§0§d§b§ls§x§3§7§0§0§c§8§lt§x§4§9§0§0§b§6§lf§x§5§b§0§0§a§4§lu§x§6§d§0§0§9§2§ll§x§8§0§0§0§8§0§l_§x§9§2§0§0§6§d§ll§x§a§4§0§0§5§b§lo§x§b§6§0§0§4§9§lv§x§c§8§0§0§3§7§le§x§d§b§0§0§2§4§l_§x§e§d§0§0§1§2§l(§x§f§f§0§0§0§0§l=
        at java.util.regex.Pattern.error(Pattern.java:2204) ~[?:?]
        at java.util.regex.Pattern.accept(Pattern.java:2054) ~[?:?]
        at java.util.regex.Pattern.group0(Pattern.java:3232) ~[?:?]
        at java.util.regex.Pattern.sequence(Pattern.java:2300) ~[?:?]
        at java.util.regex.Pattern.expr(Pattern.java:2245) ~[?:?]
        at java.util.regex.Pattern.compile(Pattern.java:1945) ~[?:?]
        at java.util.regex.Pattern.<init>(Pattern.java:1576) ~[?:?]
        at java.util.regex.Pattern.compile(Pattern.java:1101) ~[?:?]
        at ru.brikster.chatty.chat.message.transform.stage.post.MentionsTransformStrategy.lambda$patternForPlayer$0(MentionsTransformStrategy.java:124) ~[Chatty-3.0.0-SNAPSHOT.jar:?]
        at ru.brikster.chatty.shaded.com.google.common.cache.LocalCache$LocalManualCache$1.load(LocalCache.java:4853) ~[Chatty-3.0.0-SNAPSHOT.jar:?]
        at ru.brikster.chatty.shaded.com.google.common.cache.LocalCache$LoadingValueReference.loadFuture(LocalCache.java:3529) ~[Chatty-3.0.0-SNAPSHOT.jar:?]
        at ru.brikster.chatty.shaded.com.google.common.cache.LocalCache$Segment.loadSync(LocalCache.java:2278) ~[Chatty-3.0.0-SNAPSHOT.jar:?]
        at ru.brikster.chatty.shaded.com.google.common.cache.LocalCache$Segment.lockedGetOrLoad(LocalCache.java:2155) ~[Chatty-3.0.0-SNAPSHOT.jar:?]
        at ru.brikster.chatty.shaded.com.google.common.cache.LocalCache$Segment.get(LocalCache.java:2045) ~[Chatty-3.0.0-SNAPSHOT.jar:?]
        ... 25 more

**Comment by DimaSergeew** [comment]
Closing as stale.
