### ISSUE TITLE
Crash on private message

### ISSUE THREAD

**Issue by thisismavver** [Brikster/Chatty#336]
when someone tries to send a private message, the server crashes with the message: 
---- Minecraft Crash Report ----
// Daisy, daisy...
// 
// DO NOT REPORT THIS TO PAPER! REPORT TO PURPUR INSTEAD!
// 

Time: 2024-10-29 20:13:44
Description: Exception in server tick loop

java.lang.ExceptionInInitializerError
	at Chatty.jar//ru.mrbrikster.chatty.util.textapi.NMSUtil.<clinit>(NMSUtil.java:22)
	at Chatty.jar//ru.mrbrikster.chatty.json.fanciful.FancyMessage.send(FancyMessage.java:582)
	at Chatty.jar//ru.mrbrikster.chatty.json.fanciful.FancyMessage.send(FancyMessage.java:594)
	at Chatty.jar//ru.mrbrikster.chatty.commands.pm.PrivateMessageCommand.handlePrivateMessage(PrivateMessageCommand.java:123)
	at Chatty.jar//ru.mrbrikster.chatty.commands.pm.MsgCommand.handle(MsgCommand.java:62)
	at Chatty.jar//ru.mrbrikster.chatty.shaded.baseplugin.commands.BukkitCommand.execute(BukkitCommand.java:47)
	at io.papermc.paper.command.brigadier.bukkit.BukkitCommandNode$BukkitBrigCommand.run(BukkitCommandNode.java:91)
	at com.mojang.brigadier.context.ContextChain.runExecutable(ContextChain.java:73)
	at net.minecraft.commands.execution.tasks.ExecuteCommand.execute(ExecuteCommand.java:30)
	at net.minecraft.commands.execution.tasks.ExecuteCommand.execute(ExecuteCommand.java:13)
	at net.minecraft.commands.execution.UnboundEntryAction.lambda$bind$0(UnboundEntryAction.java:8)
	at net.minecraft.commands.execution.CommandQueueEntry.execute(CommandQueueEntry.java:5)
	at net.minecraft.commands.execution.ExecutionContext.runCommandQueue(ExecutionContext.java:103)
	at net.minecraft.commands.Commands.executeCommandInContext(Commands.java:451)
	at net.minecraft.commands.Commands.performCommand(Commands.java:358)
	at net.minecraft.commands.Commands.performCommand(Commands.java:345)
	at net.minecraft.commands.Commands.performCommand(Commands.java:340)
	at net.minecraft.server.network.ServerGamePacketListenerImpl.performUnsignedChatCommand(ServerGamePacketListenerImpl.java:2297)
	at net.minecraft.server.network.ServerGamePacketListenerImpl.lambda$handleChatCommand$15(ServerGamePacketListenerImpl.java:2271)
	at net.minecraft.server.TickTask.run(TickTask.java:18)
	at net.minecraft.util.thread.BlockableEventLoop.doRunTask(BlockableEventLoop.java:151)
	at net.minecraft.util.thread.ReentrantBlockableEventLoop.doRunTask(ReentrantBlockableEventLoop.java:24)
	at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:1581)
	at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:201)
	at net.minecraft.util.thread.BlockableEventLoop.pollTask(BlockableEventLoop.java:125)
	at net.minecraft.server.MinecraftServer.pollTaskInternal(MinecraftServer.java:1558)
	at net.minecraft.server.MinecraftServer.pollTask(MinecraftServer.java:1551)
	at net.minecraft.util.thread.BlockableEventLoop.runAllTasks(BlockableEventLoop.java:114)
	at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1673)
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1342)
	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:333)
	at java.base/java.lang.Thread.run(Thread.java:1583)
Caused by: java.lang.StringIndexOutOfBoundsException: Range [23, 22) out of bounds for length 22
	at java.base/jdk.internal.util.Preconditions$1.apply(Preconditions.java:55)
	at java.base/jdk.internal.util.Preconditions$1.apply(Preconditions.java:52)
	at java.base/jdk.internal.util.Preconditions$4.apply(Preconditions.java:213)
	at java.base/jdk.internal.util.Preconditions$4.apply(Preconditions.java:210)
	at java.base/jdk.internal.util.Preconditions.outOfBounds(Preconditions.java:98)
	at java.base/jdk.internal.util.Preconditions.outOfBoundsCheckFromToIndex(Preconditions.java:112)
	at java.base/jdk.internal.util.Preconditions.checkFromToIndex(Preconditions.java:349)
	at java.base/java.lang.String.checkBoundsBeginEnd(String.java:4865)
	at java.base/java.lang.String.substring(String.java:2834)
	at java.base/java.lang.String.substring(String.java:2807)
	at Chatty.jar//ru.mrbrikster.chatty.util.textapi.NMSUtil$ServerPackage.getServerVersion(NMSUtil.java:225)
	at Chatty.jar//ru.mrbrikster.chatty.util.textapi.NMSUtil$ServerPackage.<clinit>(NMSUtil.java:215)
	... 32 more

**Comment by thisismavver** [comment]
Server: Paper 1.21.1
Plugin: 2.19.14

**Comment by kesel22** [comment]
Такаяже ошибка

**Comment by c1oudychan** [comment]
Try Chatty v3: https://github.com/Brikster/Chatty/actions/runs/11573691185
