### ISSUE TITLE
При попытке написать цветное сообщение, в чате ничего не происходит, а в консоли ошибка. Пожалуйста, хелп!

### ISSUE THREAD

**Issue by shypunkkk** [Brikster/Chatty#339]
![image](https://github.com/user-attachments/assets/4f1ef085-82ec-4360-ab97-f8c634b01c87)

[04:58:49 ERROR]: [ru.brikster.chatty.chat.executor.LegacyEventExecutor] Cannot handle chat event
ru.brikster.chatty.shaded.net.kyori.adventure.text.minimessage.internal.parser.ParsingExceptionImpl: Legacy formatting codes have been detected in a MiniMessage string - this is unsupported behaviour. Please refer to the Adventure documentation (https://docs.advntr.dev) for more information.
        §6123
        ^^
        at Chatty-3.0.0-SNAPSHOT.jar/ru.brikster.chatty.shaded.net.kyori.adventure.text.minimessage.internal.parser.TokenParser.parseString(TokenParser.java:170) ~[Chatty-3.0.0-SNAPSHOT.jar:?]
        at Chatty-3.0.0-SNAPSHOT.jar/ru.brikster.chatty.shaded.net.kyori.adventure.text.minimessage.internal.parser.TokenParser.resolvePreProcessTags(TokenParser.java:112) ~[Chatty-3.0.0-SNAPSHOT.jar:?]
        at Chatty-3.0.0-SNAPSHOT.jar/ru.brikster.chatty.shaded.net.kyori.adventure.text.minimessage.MiniMessageParser.parseToTree(MiniMessageParser.java:195) ~[Chatty-3.0.0-SNAPSHOT.jar:?]
        at Chatty-3.0.0-SNAPSHOT.jar/ru.brikster.chatty.shaded.net.kyori.adventure.text.minimessage.MiniMessageParser.parseFormat(MiniMessageParser.java:209) ~[Chatty-3.0.0-SNAPSHOT.jar:?]
        at Chatty-3.0.0-SNAPSHOT.jar/ru.brikster.chatty.shaded.net.kyori.adventure.text.minimessage.MiniMessageImpl.deserialize(MiniMessageImpl.java:80) ~[Chatty-3.0.0-SNAPSHOT.jar:?]
        at Chatty-3.0.0-SNAPSHOT.jar/ru.brikster.chatty.shaded.net.kyori.adventure.text.minimessage.MiniMessageImpl.deserialize(MiniMessageImpl.java:46) ~[Chatty-3.0.0-SNAPSHOT.jar:?]
        at Chatty-3.0.0-SNAPSHOT.jar/ru.brikster.chatty.chat.construct.ComponentFromContextConstructorImpl.construct(ComponentFromContextConstructorImpl.java:35) ~[Chatty-3.0.0-SNAPSHOT.jar:?]
        at Chatty-3.0.0-SNAPSHOT.jar/ru.brikster.chatty.chat.executor.LegacyEventExecutor.sendProcessedMessage(LegacyEventExecutor.java:356) ~[Chatty-3.0.0-SNAPSHOT.jar:?]
        at Chatty-3.0.0-SNAPSHOT.jar/ru.brikster.chatty.chat.executor.LegacyEventExecutor.handleFinishedEarlyContextEvent(LegacyEventExecutor.java:219) ~[Chatty-3.0.0-SNAPSHOT.jar:?]
        at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor34.execute(Unknown Source) ~[?:?]
        at org.bukkit.plugin.EventExecutor$2.execute(EventExecutor.java:77) ~[paper-mojangapi-1.21.1-R0.1-SNAPSHOT.jar:?]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[paper-mojangapi-1.21.1-R0.1-SNAPSHOT.jar:1.21.1-2327-4b57bed]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[paper-mojangapi-1.21.1-R0.1-SNAPSHOT.jar:?]
        at io.papermc.paper.plugin.manager.PaperEventManager.callEvent(PaperEventManager.java:54) ~[purpur-1.21.1.jar:1.21.1-2327-4b57bed]
        at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.callEve
nt(PaperPluginManagerImpl.java:131) ~[purpur-1.21.1.jar:1.21.1-2327-4b57bed]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:630) ~[paper-mojangapi-1.21.1-R0.1-SNAPSHOT.jar:?]
        at io.papermc.paper.adventure.ChatProcessor.post(ChatProcessor.java:378) ~[purpur-1.21.1.jar:1.21.1-2327-4b57bed]
        at io.papermc.paper.adventure.ChatProcessor.process(ChatProcessor.java:85) ~[purpur-1.21.1.jar:1.21.1-2327-4b57bed]
        at net.minecraft.server.network.ServerGamePacketListenerImpl.chat(ServerGamePacketListenerImpl.java:2493) ~[purpur-1.21.1.jar:1.21.1-2327-4b57bed]
        at net.minecraft.server.network.ServerGamePacketListenerImpl.broadcastChatMessage(ServerGamePacketListenerImpl.java:2609) ~[purpur-1.21.1.jar:1.21.1-2327-4b57bed]
        at net.minecraft.server.network.ServerGamePacketListenerImpl.lambda$handleChat$13(ServerGamePacketListenerImpl.java:2257) ~[purpur-1.21.1.jar:1.21.1-2327-4b57bed]
        at net.minecraft.util.FutureChain.lambda$append$1(FutureChain.java:25) ~[purpur-1.21.1.jar:1.21.1-2327-4b57bed]
        at java.base/java.util.concurrent.CompletableFuture$UniAccept.tryFire(CompletableFuture.java:718) ~[?:?]
        at java.base/java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:482) ~[?:?]
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144) ~[?:?]
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642) ~[?:?]
        at java.base/java.lang.Thread.run(Thread.java:1583) ~[?:?]

**Comment by shypunkkk** [comment]
Разобрался, что цветные сообщения работают, если писать код цвета в виде &#9FF012сообщение. Но остался вопрос можно ли ещё как-то врубить поддержку дефолтных цветов Essentials? Типа &e жёлтый &4 красный и так далее?
