### ISSUE TITLE
Не рабоют цветовые коды когда пишешь в чат

### ISSUE THREAD

**Issue by Frutik349** [Brikster/Chatty#346]
```
[21:48:27 ERROR]: [ru.brikster.chatty.chat.executor.LegacyEventExecutor] Cannot handle chat event
ru.brikster.chatty.shaded.net.kyori.adventure.text.minimessage.internal.parser.ParsingExceptionImpl: Legacy formatting codes have been detected in a MiniMessage string - this is unsupported behaviour. Please refer to the Adventure documentation (https://docs.advntr.dev) for more information.
        §c§lЧат
        ^^
        at ru.brikster.chatty.shaded.net.kyori.adventure.text.minimessage.internal.parser.TokenParser.parseString(TokenParser.java:170) ~[?:?]
        at ru.brikster.chatty.shaded.net.kyori.adventure.text.minimessage.internal.parser.TokenParser.resolvePreProcessTags(TokenParser.java:112) ~[?:?]
        at ru.brikster.chatty.shaded.net.kyori.adventure.text.minimessage.MiniMessageParser.parseToTree(MiniMessageParser.java:195) ~[?:?]
        at ru.brikster.chatty.shaded.net.kyori.adventure.text.minimessage.MiniMessageParser.parseFormat(MiniMessageParser.java:209) ~[?:?]
        at ru.brikster.chatty.shaded.net.kyori.adventure.text.minimessage.MiniMessageImpl.deserialize(MiniMessageImpl.java:80) ~[?:?]
        at ru.brikster.chatty.shaded.net.kyori.adventure.text.minimessage.MiniMessageImpl.deserialize(MiniMessageImpl.java:46) ~[?:?]
        at ru.brikster.chatty.chat.construct.ComponentFromContextConstructorImpl.construct(ComponentFromContextConstructorImpl.java:35) ~[?:?]
        at ru.brikster.chatty.chat.executor.LegacyEventExecutor.sendProcessedMessage(LegacyEventExecutor.java:356) ~[?:?]
        at ru.brikster.chatty.chat.executor.LegacyEventExecutor.handleFinishedEarlyContextEvent(LegacyEventExecutor.java:219) ~[?:?]
        at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor285.execute(Unknown Source) ~[?:?]
        at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:69) ~[patched_1.16.5.jar:git-Purpur-1171]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:76) ~[patched_1.16.5.jar:git-Purpur-1171]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[patched_1.16.5.jar:git-Purpur-1171]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:624) ~[patched_1.16.5.jar:git-Purpur-1171]
        at io.papermc.paper.adventure.ChatProcessor.post(ChatProcessor.java:225) ~[patched_1.16.5.jar:git-Purpur-1171]
        at io.papermc.paper.adventure.ChatProcessor.processingLegacyFirst(ChatProcessor.java:107) ~[patched_1.16.5.jar:git-Purpur-1171]
        at io.papermc.paper.adventure.ChatProcessor.process(ChatProcessor.java:65) ~[patched_1.16.5.jar:git-Purpur-1171]
        at net.minecraft.server.v1_16_R3.PlayerConnection.chat(PlayerConnection.java:2232) ~[patched_1.16.5.jar:git-Purpur-1171]
        at net.minecraft.server.v1_16_R3.PlayerConnection.c(PlayerConnection.java:2147) ~[patched_1.16.5.jar:git-Purpur-1171]
        at net.minecraft.server.v1_16_R3.PlayerConnection.a(PlayerConnection.java:2085) ~[patched_1.16.5.jar:git-Purpur-1171]
        at net.minecraft.server.v1_16_R3.PacketPlayInChat$1.run(PacketPlayInChat.java:43) ~[patched_1.16.5.jar:git-Purpur-1171]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539) ~[?:?]
        at java.util.concurrent.FutureTask.run(FutureTask.java:264) ~[?:?]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) [?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) [?:?]
        at java.lang.Thread.run(Thread.java:840) [?:?]
```

**Comment by topbars** [comment]
тоже самое
