### ISSUE TITLE
Not working PAPI placeholders.

### ISSUE THREAD

**Issue by iBuseWinner** [Brikster/Chatty#47]
Hi.
Paper 1.15.2
Chatty 2.16.1
In config I tried to place %deluxetags_tag%, but when I trying to send a message in chat, I gets error in console:
`[14:46:23 ERROR]: Could not pass event AsyncPlayerChatEvent to Chatty v2.16.1
java.util.UnknownFormatConversionException: Conversion = ' '
        at org.bukkit.event.player.AsyncPlayerChatEvent.setFormat(AsyncPlayerChatEvent.java:101) ~[patched_1.15.2.jar:git-Paper-121]
        at ru.mrbrikster.chatty.chat.ChatListener.onChat(ChatListener.java:160) ~[?:?]
        at ru.mrbrikster.chatty.chat.ChatListener.execute(ChatListener.java:97) ~[?:?]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:76) ~[patched_1.15.2.jar:git-Paper-121]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[patched_1.15.2.jar:git-Paper-121]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:559) ~[patched_1.15.2.jar:git-Paper-121]
        at net.minecraft.server.v1_15_R1.PlayerConnection.chat(PlayerConnection.java:1734) ~[patched_1.15.2.jar:git-Paper-121]
        at net.minecraft.server.v1_15_R1.PlayerConnection.a(PlayerConnection.java:1649) ~[patched_1.15.2.jar:git-Paper-121]
        at net.minecraft.server.v1_15_R1.PacketPlayInChat$1.run(PacketPlayInChat.java:41) ~[patched_1.15.2.jar:git-Paper-121]
        at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) ~[?:1.8.0_211]
        at java.util.concurrent.FutureTask.run(Unknown Source) ~[?:1.8.0_211]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source) [?:1.8.0_211]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source) [?:1.8.0_211]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_211]`

When I am trying to use {deluxetags_tag}, that placeholder isn't working.

**Comment by iBuseWinner** [comment]
P.s. /papi parse me %deluxetags_tag% shows my active tag without any errors.
In plugin `TAB` I didn't get any errors.

**Comment by Brikster** [comment]
Have a good day. Latest version of Chatty now parses placeholders from such format: "%placeholder%".

**Comment by Brikster** [comment]
Please, send me a part of your "config.yml" file ("chats" section)

**Comment by iBuseWinner** [comment]
`chats:
  hub:
    enable: true
    format: '{prefix} {player} {suffix}%deluxetags_tag% &e→ &7{message}'
    range: -2
    cooldown: -1`

**Comment by Brikster** [comment]
What version of PlaceholderAPI?
Is there "[Chatty] PlaceholderAPI has successful hooked." in logs at startup?

**Comment by iBuseWinner** [comment]
PAPI 2.10.4
Yes, that line exists.

**Comment by Brikster** [comment]
What "/papi parse me %deluxetags_tag%" command displays?

**Comment by iBuseWinner** [comment]
My active tag (default from config)
![image](https://user-images.githubusercontent.com/44753872/75625489-c209c700-5bcf-11ea-9d60-dad32b60ef91.png)

**Comment by Brikster** [comment]
Strange. Are there any other errors in console?

**Comment by iBuseWinner** [comment]
When use /papi parse - no
When try to chat - yes

**Comment by iBuseWinner** [comment]
Just for test tried to change {prefix} {player} and {suffix} and now it works fine.
Now I use that format:
`%vault_rankprefix% %player_name% &f→ %vault_ranksuffix%%deluxetags_tag% &e→ &7{message}`
