### ISSUE TITLE
Could not pass event AsyncPlayerChatEvent to Chatty v2.18

### ISSUE THREAD

**Issue by LeetPlm4** [Brikster/Chatty#64]
при попытке написать в чат настроенной для банжи выдает эту ошибку:

```
Could not pass event AsyncPlayerChatEvent to Chatty v2.18
org.bukkit.plugin.messaging.ChannelNotRegisteredException: Attempted to send a plugin message through the unregistered channel `BungeeCord'.
	at org.bukkit.plugin.messaging.StandardMessenger.validatePluginMessage(StandardMessenger.java:544) ~[patched_1.16.1.jar:git-Paper-82]
	at org.bukkit.craftbukkit.v1_16_R1.entity.CraftPlayer.sendPluginMessage(CraftPlayer.java:1510) ~[patched_1.16.1.jar:git-Paper-82]
	at ru.mrbrikster.chatty.bungee.BungeeBroadcaster.broadcast(BungeeBroadcaster.java:23) ~[?:?]
	at ru.mrbrikster.chatty.chat.ChatListener.onChat(ChatListener.java:269) ~[?:?]
	at ru.mrbrikster.chatty.chat.ChatListener.execute(ChatListener.java:95) ~[?:?]
	at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:76) ~[patched_1.16.1.jar:git-Paper-82]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[patched_1.16.1.jar:git-Paper-82]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:607) ~[patched_1.16.1.jar:git-Paper-82]
	at net.minecraft.server.v1_16_R1.PlayerConnection.chat(PlayerConnection.java:1821) ~[patched_1.16.1.jar:git-Paper-82]
	at net.minecraft.server.v1_16_R1.PlayerConnection.a(PlayerConnection.java:1736) ~[patched_1.16.1.jar:git-Paper-82]
	at net.minecraft.server.v1_16_R1.PacketPlayInChat$1.run(PacketPlayInChat.java:41) ~[patched_1.16.1.jar:git-Paper-82]
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) ~[?:1.8.0_251]
	at java.util.concurrent.FutureTask.run(Unknown Source) ~[?:1.8.0_251]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source) [?:1.8.0_251]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source) [?:1.8.0_251]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_251]
[16:14:54] [Async Chat Thread - #5/INFO]: [#] LLLL: asdas
```

Установлен на всех серверах. на банже включительно (верися для банжи).
Конфиги везде идентичны.

git-Paper-82 (1.16.1-R0.1-SNAPSHOT)

Конфиг (частично)

```
  bunge:
    enable: true
    format: '[#] {prefix}{player}{suffix}: {message}'
    range: -3
    symbol: '*'
    cooldown: 10
    money: 10
    command: 'maxchat'
```
```
  bungeecord: true
```
```
config-version: '2.0'

# ******************************************************
# * Chatty (version 2.18)
```

**Comment by Brikster** [comment]
Привет. В spigot.yml параметр bungeecord включен ?

**Comment by LeetPlm4** [comment]
> Привет. В spigot.yml параметр bungeecord включен ?

В жизни не поверишь... включен! хД
Фактически живая банжа с ботфильтром и 2  работающих сервера.
может больше инфы дать? если да то что?
В банже плагин жив. 
![image](https://user-images.githubusercontent.com/46025416/87433047-82c59b00-c5f1-11ea-87f4-2c80891ecc51.png)

На серверах все тоже вроде норм.
![image](https://user-images.githubusercontent.com/46025416/87433173-ad175880-c5f1-11ea-854e-1e40c5af6009.png)

Работает все кроме банж чата. Меняла символ \ # Chat listener priority. \ и цену убирала.

**Comment by Brikster** [comment]
Пилю сейчас апдейт. В 1.16 поменяли что-то, возможно. Проверю и пофикшу)

**Comment by Brikster** [comment]
Должно быть пофикшено в актуальных версиях.
