### ISSUE TITLE
22 Action ивенты АсинхронЧата, выхода, захода,

### ISSUE THREAD

**Issue by LeetPlm4** [Brikster/Chatty#93]
Тестеры нужны?
[Java CI #22: Commit 1b71770](https://github.com/Brikster/Chatty/actions/runs/191662900)
![image](https://user-images.githubusercontent.com/46025416/89127354-94fe6f00-d4f5-11ea-9a60-d52b14fe5424.png)

![image](https://user-images.githubusercontent.com/46025416/89127217-8cf1ff80-d4f4-11ea-93ab-6ab09526b827.png)
![image](https://user-images.githubusercontent.com/46025416/89127278-025dd000-d4f5-11ea-8bbd-fcc0803d9407.png)
![image](https://user-images.githubusercontent.com/46025416/89127287-0ee22880-d4f5-11ea-91cf-a991405b7237.png)

**Comment by imDaniX** [comment]
Поправится, если примут PR. Полагаю, баг явился с новой системой singleton'ов от @Brikster. На мой взгляд, она выглядит.. странно. Может и удобно, но явно ломается читабельность кода. Впрочем, не мне судить.

**Comment by Brikster** [comment]
Согласен, выглядит странно. Просто устал в конструкторах кучу этих параметров держать, дико неудобно. Когда-нибудь потом надо основательно и по-правильному накодить, но пока не до этого)

**Comment by LeetPlm4** [comment]
И так, [23 actions](https://github.com/Brikster/Chatty/actions/runs/192338972). 

- [x] Локальный\Глобальный
- [x] вход\выход
- [x] плейсхолдеры в чате

- [ ] Банжачатик (старый Chatty-BungeeCord.jar?)
![image](https://user-images.githubusercontent.com/46025416/89164330-9d02f100-d57f-11ea-9e9a-dc22f5e162b6.png)
Даже не пишет о том что меня не услышали.
```
[Async Chat Thread - #2/ERROR]: Could not pass event AsyncPlayerChatEvent to Chatty v2.19-SNAPSHOT
org.bukkit.plugin.messaging.ChannelNotRegisteredException: Attempted to send a plugin message through the unregistered channel `BungeeCord'.
	at org.bukkit.plugin.messaging.StandardMessenger.validatePluginMessage(StandardMessenger.java:544) ~[patched_1.16.1.jar:git-Paper-82]
	at org.bukkit.craftbukkit.v1_16_R1.entity.CraftPlayer.sendPluginMessage(CraftPlayer.java:1510) ~[patched_1.16.1.jar:git-Paper-82]
	at ru.mrbrikster.chatty.bungee.BungeeBroadcaster.broadcast(BungeeBroadcaster.java:32) ~[?:?]
	at ru.mrbrikster.chatty.chat.ChatListener.onChat(ChatListener.java:189) ~[?:?]
	at ru.mrbrikster.chatty.chat.ChatListener.execute(ChatListener.java:95) ~[?:?]
	at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:76) ~[patched_1.16.1.jar:git-Paper-82]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[patched_1.16.1.jar:git-Paper-82]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:607) ~[patched_1.16.1.jar:git-Paper-82]
	at net.minecraft.server.v1_16_R1.PlayerConnection.chat(PlayerConnection.java:1821) ~[patched_1.16.1.jar:git-Paper-82]
	at net.minecraft.server.v1_16_R1.PlayerConnection.a(PlayerConnection.java:1736) ~[patched_1.16.1.jar:git-Paper-82]
	at net.minecraft.server.v1_16_R1.PacketPlayInChat$1.run(PacketPlayInChat.java:41) ~[patched_1.16.1.jar:git-Paper-82]
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) ~[?:1.8.0_251]
	at java.util.concurrent.FutureTask.run(Unknown Source) ~[?:1.8.0_251]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source) [?:1.8.0_251]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source) [?:1.8.0_251]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_251]
[11:26:48] [Async Chat Thread - #2/ERROR]: Could not pass event AsyncPlayerChatEvent to Chatty v2.19-SNAPSHOT
java.lang.NullPointerException: null
	at ru.mrbrikster.chatty.chat.ChatListener.onSpyMessage(ChatListener.java:275) ~[?:?]
	at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor63.execute(Unknown Source) ~[?:?]
	at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:69) ~[patched_1.16.1.jar:git-Paper-82]
	at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:76) ~[patched_1.16.1.jar:git-Paper-82]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[patched_1.16.1.jar:git-Paper-82]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:607) ~[patched_1.16.1.jar:git-Paper-82]
	at net.minecraft.server.v1_16_R1.PlayerConnection.chat(PlayerConnection.java:1821) ~[patched_1.16.1.jar:git-Paper-82]
	at net.minecraft.server.v1_16_R1.PlayerConnection.a(PlayerConnection.java:1736) ~[patched_1.16.1.jar:git-Paper-82]
	at net.minecraft.server.v1_16_R1.PacketPlayInChat$1.run(PacketPlayInChat.java:41) ~[patched_1.16.1.jar:git-Paper-82]
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) ~[?:1.8.0_251]
	at java.util.concurrent.FutureTask.run(Unknown Source) ~[?:1.8.0_251]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source) [?:1.8.0_251]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source) [?:1.8.0_251]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_251]
[11:26:48] [Async Chat Thread - #2/INFO]: [#] ?FLY? ?FLY? plm4: лоль
```
- [ ] Цвета ( юзаю как в гайде )
![image](https://user-images.githubusercontent.com/46025416/89164271-8c527b00-d57f-11ea-8327-e7cb00a1aede.png)

```
[11:47:07] [Async Chat Thread - #6/INFO]: [L] ?FLY? ?FLY? §xPLM4: {#12ABCD}text
[11:47:25] [Async Chat Thread - #6/INFO]: [L] ?FLY? ?FLY? §xPLM4: {#ffffff}text
[11:48:16] [Async Chat Thread - #6/ERROR]: Could not pass event AsyncPlayerChatEvent to Chatty v2.19-SNAPSHOT
java.lang.NoSuchMethodError: net.md_5.bungee.api.ChatColor.getColor()Ljava/awt/Color;
	at ru.mrbrikster.chatty.util.TextUtil.stylish(TextUtil.java:77) ~[?:?]
	at ru.mrbrikster.chatty.chat.ChatListener.onSpyMessage(ChatListener.java:278) ~[?:?]
	at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor63.execute(Unknown Source) ~[?:?]
	at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:69) ~[patched_1.16.1.jar:git-Paper-82]
	at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:76) ~[patched_1.16.1.jar:git-Paper-82]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[patched_1.16.1.jar:git-Paper-82]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:607) ~[patched_1.16.1.jar:git-Paper-82]
	at net.minecraft.server.v1_16_R1.PlayerConnection.chat(PlayerConnection.java:1821) ~[patched_1.16.1.jar:git-Paper-82]
	at net.minecraft.server.v1_16_R1.PlayerConnection.a(PlayerConnection.java:1736) ~[patched_1.16.1.jar:git-Paper-82]
	at net.minecraft.server.v1_16_R1.PacketPlayInChat$1.run(PacketPlayInChat.java:41) ~[patched_1.16.1.jar:git-Paper-82]
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) ~[?:1.8.0_251]
	at java.util.concurrent.FutureTask.run(Unknown Source) ~[?:1.8.0_251]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source) [?:1.8.0_251]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source) [?:1.8.0_251]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_251]
[11:48:16] [Async Chat Thread - #6/INFO]: [L] ?FLY? ?FLY? §xPLM4: {#ffffff:#0039a6:#d52b1e This is awesome tricolor gradient}
[11:48:54] [Async Chat Thread - #6/ERROR]: Could not pass event AsyncPlayerChatEvent to Chatty v2.19-SNAPSHOT
java.lang.NoSuchMethodError: net.md_5.bungee.api.ChatColor.getColor()Ljava/awt/Color;
	at ru.mrbrikster.chatty.util.TextUtil.stylish(TextUtil.java:77) ~[?:?]
	at ru.mrbrikster.chatty.chat.ChatListener.onSpyMessage(ChatListener.java:278) ~[?:?]
	at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor63.execute(Unknown Source) ~[?:?]
	at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:69) ~[patched_1.16.1.jar:git-Paper-82]
	at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:76) ~[patched_1.16.1.jar:git-Paper-82]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[patched_1.16.1.jar:git-Paper-82]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:607) ~[patched_1.16.1.jar:git-Paper-82]
	at net.minecraft.server.v1_16_R1.PlayerConnection.chat(PlayerConnection.java:1821) ~[patched_1.16.1.jar:git-Paper-82]
	at net.minecraft.server.v1_16_R1.PlayerConnection.a(PlayerConnection.java:1736) ~[patched_1.16.1.jar:git-Paper-82]
	at net.minecraft.server.v1_16_R1.PacketPlayInChat$1.run(PacketPlayInChat.java:41) ~[patched_1.16.1.jar:git-Paper-82]
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) ~[?:1.8.0_251]
	at java.util.concurrent.FutureTask.run(Unknown Source) ~[?:1.8.0_251]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source) [?:1.8.0_251]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source) [?:1.8.0_251]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_251]
[11:48:54] [Async Chat Thread - #6/INFO]: [L] ?FLY? ?FLY? §xPLM4: {#d818c4:#ae6be6:#0f7584:#7983a7:#a793ba:#34344b This is multicolor gradient}
```

Сейчас проверю json, помню там у кого-то ошибка с ними была

**Comment by LeetPlm4** [comment]
- [ ]Json

```
[11:59:50] [Async Chat Thread - #9/ERROR]: Could not pass event AsyncPlayerChatEvent to Chatty v2.19-SNAPSHOT
org.bukkit.plugin.messaging.ChannelNotRegisteredException: Attempted to send a plugin message through the unregistered channel `BungeeCord'.
	at org.bukkit.plugin.messaging.StandardMessenger.validatePluginMessage(StandardMessenger.java:544) ~[patched_1.16.1.jar:git-Paper-82]
	at org.bukkit.craftbukkit.v1_16_R1.entity.CraftPlayer.sendPluginMessage(CraftPlayer.java:1510) ~[patched_1.16.1.jar:git-Paper-82]
	at ru.mrbrikster.chatty.bungee.BungeeBroadcaster.broadcast(BungeeBroadcaster.java:32) ~[?:?]
	at ru.mrbrikster.chatty.chat.ChatListener.performJsonMessage(ChatListener.java:369) ~[?:?]
	at ru.mrbrikster.chatty.chat.ChatListener.onChatMonitor(ChatListener.java:309) ~[?:?]
	at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor64.execute(Unknown Source) ~[?:?]
	at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:69) ~[patched_1.16.1.jar:git-Paper-82]
	at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:76) ~[patched_1.16.1.jar:git-Paper-82]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[patched_1.16.1.jar:git-Paper-82]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:607) ~[patched_1.16.1.jar:git-Paper-82]
	at net.minecraft.server.v1_16_R1.PlayerConnection.chat(PlayerConnection.java:1821) ~[patched_1.16.1.jar:git-Paper-82]
	at net.minecraft.server.v1_16_R1.PlayerConnection.a(PlayerConnection.java:1736) ~[patched_1.16.1.jar:git-Paper-82]
	at net.minecraft.server.v1_16_R1.PacketPlayInChat$1.run(PacketPlayInChat.java:41) ~[patched_1.16.1.jar:git-Paper-82]
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) ~[?:1.8.0_251]
	at java.util.concurrent.FutureTask.run(Unknown Source) ~[?:1.8.0_251]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source) [?:1.8.0_251]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source) [?:1.8.0_251]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_251]
[11:59:50] [Async Chat Thread - #9/INFO]: [L] ?FLY? ?FLY? §xPLM4: sda
```
Конфиг
```
json:
  enable: true
  suggest: '/msg {player} '
  tooltip:
  - '&fPlayer &e{player}'
  - '% luckperms_prefix % >> '
  - '%luckperms_prefix% '
  - '{ #ffffff }&ltext >>'
  - '{#ffffff}&ltext'
  swears:
    enable: true
    tooltip:
    - '&o{word}'
    - ''
    - '&eClick here to add word to whitelist.'
    suggest: /swears add {word}

```

**Comment by LeetPlm4** [comment]
- [x] Уведомления 
`- '{#12ABCD}&ltext %server_version% '`

![image](https://user-images.githubusercontent.com/46025416/89165982-0683ff00-d582-11ea-9002-da92f93db6d7.png)
![image](https://user-images.githubusercontent.com/46025416/89166013-10a5fd80-d582-11ea-86f5-4a083e10b9d3.png)
![image](https://user-images.githubusercontent.com/46025416/89166046-1d2a5600-d582-11ea-914e-6b1cea4075e1.png)
![image](https://user-images.githubusercontent.com/46025416/89166442-ba858a00-d582-11ea-8429-402b1f27695e.png)

**Comment by LeetPlm4** [comment]
- [ ] Сообщение с цветом но без текста 
![image](https://user-images.githubusercontent.com/46025416/89167052-96767880-d583-11ea-889c-e3c8a6cc247e.png)

```
[12:16:48] [Async Chat Thread - #12/INFO]: [L] ?FLY? ?FLY? §xPLM4: Сообщение с ванильным цветом
[12:16:59] [Async Chat Thread - #12/INFO]: [L] ?FLY? ?FLY? §xPLM4: следующее сообщение просто цвет
[12:17:06] [Async Chat Thread - #12/ERROR]: Could not pass event AsyncPlayerChatEvent to Chatty v2.19-SNAPSHOT
java.lang.NullPointerException: null
	at ru.mrbrikster.chatty.chat.ChatListener.onSpyMessage(ChatListener.java:275) ~[?:?]
	at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor63.execute(Unknown Source) ~[?:?]
	at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:69) ~[patched_1.16.1.jar:git-Paper-82]
	at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:76) ~[patched_1.16.1.jar:git-Paper-82]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[patched_1.16.1.jar:git-Paper-82]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:607) ~[patched_1.16.1.jar:git-Paper-82]
	at net.minecraft.server.v1_16_R1.PlayerConnection.chat(PlayerConnection.java:1821) ~[patched_1.16.1.jar:git-Paper-82]
	at net.minecraft.server.v1_16_R1.PlayerConnection.a(PlayerConnection.java:1736) ~[patched_1.16.1.jar:git-Paper-82]
	at net.minecraft.server.v1_16_R1.PacketPlayInChat$1.run(PacketPlayInChat.java:41) ~[patched_1.16.1.jar:git-Paper-82]
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) ~[?:1.8.0_251]
	at java.util.concurrent.FutureTask.run(Unknown Source) ~[?:1.8.0_251]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source) [?:1.8.0_251]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source) [?:1.8.0_251]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_251]
```

**Comment by imDaniX** [comment]
Режим bungeecord включен прямо со старта сервера?

**Comment by LeetPlm4** [comment]
> Режим bungeecord включен прямо со старта сервера?

Да, тестила на 2 включенных и связанных серверах. 1 был пустой на втором была я.

**Comment by imDaniX** [comment]
По поводу градиента - возможно, дело в том, что сервер устаревший стоит - сейчас у Paper билд 131, т.е. почти на 50 версий дальше.

**Comment by SSKirillSS** [comment]
Похожая проблема и с 1.12 без банжи. Поднял тестовый для проверки работы плагина с G-Actions, сразу же заспамило консоль ошибкам, ну и, короче, выключил сервер :D

**Comment by LeetPlm4** [comment]
> По поводу градиента - возможно, дело в том, что сервер устаревший стоит - сейчас у Paper билд 131, т.е. почти на 50 версий дальше.

paper 131, банжчат заработал. Градиент протещу.
